#! /usr/bin/python

#
# Description:
# ================================================================
# Time-stamp: "2022-10-03 11:44:12 trottar"
# ================================================================
#
# Author:  Richard L. Trotta III <trotta@cua.edu>
#
# Copyright (c) trottar
#
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from csv import DictReader
import sys, os

################################################################################################################################################
'''
User Inputs
'''
ROOTPrefix = sys.argv[1]
runType = sys.argv[2]
timestmp = sys.argv[3]

################################################################################################################################################
'''
ltsep package import and pathing definitions
'''

# Import package for cuts
import ltsep as lt 

p=lt.SetPath(os.path.realpath(__file__))

# Add this to all files for more dynamic pathing
USER=p.getPath("USER") # Grab user info for file finding
HOST=p.getPath("HOST")
REPLAYPATH=p.getPath("REPLAYPATH")
UTILPATH=p.getPath("UTILPATH")
ANATYPE=p.getPath("ANATYPE")
SCRIPTPATH=p.getPath("SCRIPTPATH")

################################################################################################################################################

inp_f = UTILPATH+"/scripts/efficiency/OUTPUTS/%s_%s_efficiency_data_%s.csv"  % (ROOTPrefix.replace("replay_",""),runType,timestmp)

# Converts csv data to dataframe
try:
    efficiency_data = pd.read_csv(inp_f)
except IOError:
    print("Error: %s does not appear to exist." % inp_f)
print(efficiency_data.keys())

efficiency_data_10p6 = efficiency_data[(efficiency_data['Run_Number'] >= 4865)  & (efficiency_data['Run_Number'] <= 5334)]
efficiency_data_3p8 = efficiency_data[(efficiency_data['Run_Number'] >= 6638)  & (efficiency_data['Run_Number'] <= 6857)]
efficiency_data_4p9 = efficiency_data[(efficiency_data['Run_Number'] >= 6885)  & (efficiency_data['Run_Number'] <= 7045)]
efficiency_data_6p2 = efficiency_data[(efficiency_data['Run_Number'] >= 7871)  & (efficiency_data['Run_Number'] <= 7938)]
efficiency_data_8p2 = efficiency_data[(efficiency_data['Run_Number'] >= 7978)  & (efficiency_data['Run_Number'] <= 8356)]

plt.figure(figsize=(12,8))

plt.subplot(141)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["SHMS_3/4_Trigger_Rate"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["SHMS_3/4_Trigger_Rate"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["SHMS_3/4_Trigger_Rate"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["SHMS_3/4_Trigger_Rate"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["SHMS_3/4_Trigger_Rate"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["SHMS_3/4_Trigger_Rate"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_10p6["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["SHMS_3/4_Trigger_Rate"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_3p8["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["SHMS_3/4_Trigger_Rate"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_4p9["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["SHMS_3/4_Trigger_Rate"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_6p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["SHMS_3/4_Trigger_Rate"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_8p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.ylabel('EDTM', fontsize=12)
plt.xlabel('SHMS 3/4 Trigger Rate [kHz]', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(142)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["SHMS_3/4_Trigger_Rate"],efficiency_data_10p6["SHMS_Pion_SING_TRACK_EFF"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["SHMS_3/4_Trigger_Rate"],efficiency_data_3p8["SHMS_Pion_SING_TRACK_EFF"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["SHMS_3/4_Trigger_Rate"],efficiency_data_4p9["SHMS_Pion_SING_TRACK_EFF"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["SHMS_3/4_Trigger_Rate"],efficiency_data_6p2["SHMS_Pion_SING_TRACK_EFF"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["SHMS_3/4_Trigger_Rate"],efficiency_data_8p2["SHMS_Pion_SING_TRACK_EFF"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["SHMS_3/4_Trigger_Rate"],efficiency_data_10p6["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_10p6["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["SHMS_3/4_Trigger_Rate"],efficiency_data_3p8["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_3p8["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["SHMS_3/4_Trigger_Rate"],efficiency_data_4p9["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_4p9["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["SHMS_3/4_Trigger_Rate"],efficiency_data_6p2["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_6p2["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["SHMS_3/4_Trigger_Rate"],efficiency_data_8p2["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_8p2["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.ylabel('SHMS_Pion_SING_TRACK_EFF', fontsize=12)
plt.xlabel('SHMS 3/4 Trigger Rate [kHz]', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(143)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["SHMS_3/4_Trigger_Rate"],efficiency_data_10p6["SHMS_Aero_SING_Pion_Eff"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["SHMS_3/4_Trigger_Rate"],efficiency_data_3p8["SHMS_Aero_SING_Pion_Eff"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["SHMS_3/4_Trigger_Rate"],efficiency_data_4p9["SHMS_Aero_SING_Pion_Eff"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["SHMS_3/4_Trigger_Rate"],efficiency_data_6p2["SHMS_Aero_SING_Pion_Eff"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["SHMS_3/4_Trigger_Rate"],efficiency_data_8p2["SHMS_Aero_SING_Pion_Eff"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["SHMS_3/4_Trigger_Rate"],efficiency_data_10p6["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_10p6["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["SHMS_3/4_Trigger_Rate"],efficiency_data_3p8["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_3p8["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["SHMS_3/4_Trigger_Rate"],efficiency_data_4p9["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_4p9["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["SHMS_3/4_Trigger_Rate"],efficiency_data_6p2["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_6p2["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["SHMS_3/4_Trigger_Rate"],efficiency_data_8p2["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_8p2["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.ylabel('SHMS_Aero_SING_Pion_Eff', fontsize=12)
plt.xlabel('SHMS 3/4 Trigger Rate [kHz]', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(144)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["SHMS_3/4_Trigger_Rate"],efficiency_data_10p6["SHMS_Hodo_3_of_4_EFF"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["SHMS_3/4_Trigger_Rate"],efficiency_data_3p8["SHMS_Hodo_3_of_4_EFF"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["SHMS_3/4_Trigger_Rate"],efficiency_data_4p9["SHMS_Hodo_3_of_4_EFF"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["SHMS_3/4_Trigger_Rate"],efficiency_data_6p2["SHMS_Hodo_3_of_4_EFF"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["SHMS_3/4_Trigger_Rate"],efficiency_data_8p2["SHMS_Hodo_3_of_4_EFF"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
#plt.errorbar(efficiency_data_10p6["SHMS_3/4_Trigger_Rate"],efficiency_data_10p6["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_10p6["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_3p8["SHMS_3/4_Trigger_Rate"],efficiency_data_3p8["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_3p8["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_4p9["SHMS_3/4_Trigger_Rate"],efficiency_data_4p9["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_4p9["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_6p2["SHMS_3/4_Trigger_Rate"],efficiency_data_6p2["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_6p2["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_8p2["SHMS_3/4_Trigger_Rate"],efficiency_data_8p2["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_8p2["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
plt.ylabel('SHMS_Hodo_3_of_4_EFF', fontsize=12)
plt.xlabel('SHMS 3/4 Trigger Rate [kHz]', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.tight_layout(rect=[0,0.03,1,0.95])   
plt.savefig(UTILPATH+'/scripts/efficiency/OUTPUTS/plots/SHMS_3-4_%s.png' % (ROOTPrefix.replace("replay_","")))

plt.figure(figsize=(12,8))

plt.subplot(141)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["SHMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["SHMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["SHMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["SHMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_10p6["Non_Scaler_EDTM_Live_Time_ERROR"],color='blue',zorder=3)
plt.errorbar(efficiency_data_3p8["SHMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_3p8["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["SHMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_4p9["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_6p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_8p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.ylabel('EDTM', fontsize=12)
plt.xlabel('SHMS S1X HODO Rate [kHz]', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(142)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["SHMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["SHMS_Pion_SING_TRACK_EFF"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["SHMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["SHMS_Pion_SING_TRACK_EFF"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["SHMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["SHMS_Pion_SING_TRACK_EFF"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["SHMS_Pion_SING_TRACK_EFF"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["SHMS_Pion_SING_TRACK_EFF"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["SHMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_10p6["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["SHMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_3p8["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["SHMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_4p9["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_6p2["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_8p2["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.ylabel('SHMS_Pion_SING_TRACK_EFF', fontsize=12)
plt.xlabel('SHMS S1X HODO Rate [kHz]', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(143)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["SHMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["SHMS_Aero_SING_Pion_Eff"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["SHMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["SHMS_Aero_SING_Pion_Eff"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["SHMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["SHMS_Aero_SING_Pion_Eff"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["SHMS_Aero_SING_Pion_Eff"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["SHMS_Aero_SING_Pion_Eff"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["SHMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_10p6["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["SHMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_3p8["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["SHMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_4p9["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_6p2["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_8p2["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.ylabel('SHMS_Aero_SING_Pion_Eff', fontsize=12)
plt.xlabel('SHMS S1X HODO Rate [kHz]', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(144)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["SHMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["SHMS_Hodo_3_of_4_EFF"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["SHMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["SHMS_Hodo_3_of_4_EFF"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["SHMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["SHMS_Hodo_3_of_4_EFF"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["SHMS_Hodo_3_of_4_EFF"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["SHMS_Hodo_3_of_4_EFF"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
#plt.errorbar(efficiency_data_10p6["SHMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_10p6["SHMS_Hodo_3_of_4_EFF_ERROR"],color='blue',zorder=3)
#plt.errorbar(efficiency_data_3p8["SHMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_3p8["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_4p9["SHMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_4p9["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_6p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_6p2["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_8p2["SHMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_8p2["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
plt.ylabel('SHMS_Hodo_3_of_4_EFF', fontsize=12)
plt.xlabel('SHMS S1X HODO Rate [kHz]', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.tight_layout(rect=[0,0.03,1,0.95])
plt.savefig(UTILPATH+'/scripts/efficiency/OUTPUTS/plots/SHMS_S1X_%s.png' % (ROOTPrefix.replace("replay_","")))

plt.figure(figsize=(12,8))

plt.subplot(141)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["HMS_EL-REAL_Trigger_Rate"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["HMS_EL-REAL_Trigger_Rate"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["HMS_EL-REAL_Trigger_Rate"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["HMS_EL-REAL_Trigger_Rate"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_10p6["Non_Scaler_EDTM_Live_Time_ERROR"],color='blue',zorder=3)
plt.errorbar(efficiency_data_3p8["HMS_EL-REAL_Trigger_Rate"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_3p8["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["HMS_EL-REAL_Trigger_Rate"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_4p9["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_6p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_8p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.ylabel('EDTM', fontsize=12)
plt.xlabel('HMS EL-REAL Trigger Rate [kHz]', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(142)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["HMS_EL-REAL_Trigger_Rate"],efficiency_data_10p6["HMS_Elec_SING_TRACK_EFF"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["HMS_EL-REAL_Trigger_Rate"],efficiency_data_3p8["HMS_Elec_SING_TRACK_EFF"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["HMS_EL-REAL_Trigger_Rate"],efficiency_data_4p9["HMS_Elec_SING_TRACK_EFF"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_6p2["HMS_Elec_SING_TRACK_EFF"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_8p2["HMS_Elec_SING_TRACK_EFF"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["HMS_EL-REAL_Trigger_Rate"],efficiency_data_10p6["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_10p6["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["HMS_EL-REAL_Trigger_Rate"],efficiency_data_3p8["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_3p8["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["HMS_EL-REAL_Trigger_Rate"],efficiency_data_4p9["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_4p9["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_6p2["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_6p2["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_8p2["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_8p2["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.ylabel('HMS_Elec_SING_TRACK_EFF', fontsize=12)
plt.xlabel('HMS EL-REAL Trigger Rate [kHz]', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(143)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["HMS_EL-REAL_Trigger_Rate"],efficiency_data_10p6["HMS_Cer_SING_Elec_Eff"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["HMS_EL-REAL_Trigger_Rate"],efficiency_data_3p8["HMS_Cer_SING_Elec_Eff"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["HMS_EL-REAL_Trigger_Rate"],efficiency_data_4p9["HMS_Cer_SING_Elec_Eff"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_6p2["HMS_Cer_SING_Elec_Eff"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_8p2["HMS_Cer_SING_Elec_Eff"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["HMS_EL-REAL_Trigger_Rate"],efficiency_data_10p6["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_10p6["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["HMS_EL-REAL_Trigger_Rate"],efficiency_data_3p8["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_3p8["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["HMS_EL-REAL_Trigger_Rate"],efficiency_data_4p9["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_4p9["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_6p2["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_6p2["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_8p2["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_8p2["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.ylabel('HMS_Cer_SING_Elec_Eff', fontsize=12)
plt.xlabel('HMS EL-REAL Trigger Rate [kHz]', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(144)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["HMS_EL-REAL_Trigger_Rate"],efficiency_data_10p6["HMS_Hodo_3_of_4_EFF"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["HMS_EL-REAL_Trigger_Rate"],efficiency_data_3p8["HMS_Hodo_3_of_4_EFF"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["HMS_EL-REAL_Trigger_Rate"],efficiency_data_4p9["HMS_Hodo_3_of_4_EFF"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_6p2["HMS_Hodo_3_of_4_EFF"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_8p2["HMS_Hodo_3_of_4_EFF"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
#plt.errorbar(efficiency_data_10p6["HMS_EL-REAL_Trigger_Rate"],efficiency_data_10p6["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_10p6["HMS_Hodo_3_of_4_EFF_ERROR"],color='blue',zorder=3)
#plt.errorbar(efficiency_data_3p8["HMS_EL-REAL_Trigger_Rate"],efficiency_data_3p8["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_3p8["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_4p9["HMS_EL-REAL_Trigger_Rate"],efficiency_data_4p9["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_4p9["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_6p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_6p2["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_6p2["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_8p2["HMS_EL-REAL_Trigger_Rate"],efficiency_data_8p2["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_8p2["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
plt.ylabel('HMS_Hodo_3_of_4_EFF', fontsize=12)
plt.xlabel('HMS EL-REAL Trigger Rate [kHz]', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.tight_layout(rect=[0,0.03,1,0.95])   
plt.savefig(UTILPATH+'/scripts/efficiency/OUTPUTS/plots/HMS_EL-REAL_%s.png' % (ROOTPrefix.replace("replay_","")))

plt.figure(figsize=(12,8))

plt.subplot(141)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["HMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["HMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["HMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["HMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_10p6["Non_Scaler_EDTM_Live_Time_ERROR"],color='blue',zorder=3)
plt.errorbar(efficiency_data_3p8["HMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_3p8["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["HMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_4p9["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_6p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_8p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.ylabel('EDTM', fontsize=12)
plt.xlabel('HMS S1X HODO Rate [kHz]', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(142)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["HMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["HMS_Elec_SING_TRACK_EFF"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["HMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["HMS_Elec_SING_TRACK_EFF"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["HMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["HMS_Elec_SING_TRACK_EFF"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["HMS_Elec_SING_TRACK_EFF"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["HMS_Elec_SING_TRACK_EFF"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["HMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_10p6["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["HMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_3p8["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["HMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_4p9["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_6p2["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_8p2["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.ylabel('HMS_Elec_SING_TRACK_EFF', fontsize=12)
plt.xlabel('HMS S1X HODO Rate [kHz]', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(143)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["HMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["HMS_Cer_SING_Elec_Eff"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["HMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["HMS_Cer_SING_Elec_Eff"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["HMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["HMS_Cer_SING_Elec_Eff"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["HMS_Cer_SING_Elec_Eff"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["HMS_Cer_SING_Elec_Eff"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["HMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_10p6["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["HMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_3p8["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["HMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_4p9["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_6p2["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_8p2["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.ylabel('HMS_Cer_SING_Elec_Eff', fontsize=12)
plt.xlabel('HMS S1X HODO Rate [kHz]', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(144)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["HMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["HMS_Hodo_3_of_4_EFF"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["HMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["HMS_Hodo_3_of_4_EFF"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["HMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["HMS_Hodo_3_of_4_EFF"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["HMS_Hodo_3_of_4_EFF"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["HMS_Hodo_3_of_4_EFF"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
#plt.errorbar(efficiency_data_10p6["HMS_Hodoscope_S1X_Rate"],efficiency_data_10p6["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_10p6["HMS_Hodo_3_of_4_EFF_ERROR"],color='blue',zorder=3)
#plt.errorbar(efficiency_data_3p8["HMS_Hodoscope_S1X_Rate"],efficiency_data_3p8["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_3p8["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_4p9["HMS_Hodoscope_S1X_Rate"],efficiency_data_4p9["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_4p9["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_6p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_6p2["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_6p2["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_8p2["HMS_Hodoscope_S1X_Rate"],efficiency_data_8p2["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_8p2["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
plt.ylabel('HMS_Hodo_3_of_4_EFF', fontsize=12)
plt.xlabel('HMS S1X HODO Rate [kHz]', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.tight_layout(rect=[0,0.03,1,0.95])
plt.savefig(UTILPATH+'/scripts/efficiency/OUTPUTS/plots/HMS_S1X_%s.png' % (ROOTPrefix.replace("replay_","")))

plt.figure(figsize=(12,8))

plt.subplot(141)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["COIN_Trigger_Rate"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["COIN_Trigger_Rate"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["COIN_Trigger_Rate"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["COIN_Trigger_Rate"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["COIN_Trigger_Rate"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["COIN_Trigger_Rate"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_10p6["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_3p8["COIN_Trigger_Rate"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_3p8["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_4p9["COIN_Trigger_Rate"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_4p9["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_6p2["COIN_Trigger_Rate"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_6p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_8p2["COIN_Trigger_Rate"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_8p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',linestyle='None',zorder=3)
plt.ylabel('EDTM', fontsize=12)
plt.xlabel('COIN Trigger Rate [kHz]', fontsize=12)
plt.title('COIN %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(142)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["COIN_Trigger_Rate"],efficiency_data_10p6["COIN_CPULT"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["COIN_Trigger_Rate"],efficiency_data_3p8["COIN_CPULT"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["COIN_Trigger_Rate"],efficiency_data_4p9["COIN_CPULT"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["COIN_Trigger_Rate"],efficiency_data_6p2["COIN_CPULT"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["COIN_Trigger_Rate"],efficiency_data_8p2["COIN_CPULT"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["COIN_Trigger_Rate"],efficiency_data_10p6["COIN_CPULT"],yerr=efficiency_data_10p6["COIN_CPULT_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_3p8["COIN_Trigger_Rate"],efficiency_data_3p8["COIN_CPULT"],yerr=efficiency_data_3p8["COIN_CPULT_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_4p9["COIN_Trigger_Rate"],efficiency_data_4p9["COIN_CPULT"],yerr=efficiency_data_4p9["COIN_CPULT_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_6p2["COIN_Trigger_Rate"],efficiency_data_6p2["COIN_CPULT"],yerr=efficiency_data_6p2["COIN_CPULT_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_8p2["COIN_Trigger_Rate"],efficiency_data_8p2["COIN_CPULT"],yerr=efficiency_data_8p2["COIN_CPULT_ERROR"],color='black',linestyle='None',zorder=3)

plt.ylabel('COIN CPULT', fontsize=12)
plt.xlabel('COIN Trigger Rate [kHz]', fontsize=12)
plt.title('COIN %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(143)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["COIN_Trigger_Rate"],efficiency_data_10p6["SHMS_3/4_Trigger_Rate"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["COIN_Trigger_Rate"],efficiency_data_3p8["SHMS_3/4_Trigger_Rate"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["COIN_Trigger_Rate"],efficiency_data_4p9["SHMS_3/4_Trigger_Rate"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["COIN_Trigger_Rate"],efficiency_data_6p2["SHMS_3/4_Trigger_Rate"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["COIN_Trigger_Rate"],efficiency_data_8p2["SHMS_3/4_Trigger_Rate"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.ylabel('SHMS 3/4 Trigger Rate [kHz]', fontsize=12)
plt.xlabel('COIN Trigger Rate [kHz]', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(144)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["COIN_Trigger_Rate"],efficiency_data_10p6["HMS_EL-REAL_Trigger_Rate"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["COIN_Trigger_Rate"],efficiency_data_3p8["HMS_EL-REAL_Trigger_Rate"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["COIN_Trigger_Rate"],efficiency_data_4p9["HMS_EL-REAL_Trigger_Rate"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["COIN_Trigger_Rate"],efficiency_data_6p2["HMS_EL-REAL_Trigger_Rate"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["COIN_Trigger_Rate"],efficiency_data_8p2["HMS_EL-REAL_Trigger_Rate"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.ylabel('HMS EL-REAL Trigger Rate [kHz]', fontsize=12)
plt.xlabel('COIN Trigger Rate [kHz]', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.tight_layout(rect=[0,0.03,1,0.95])
plt.savefig(UTILPATH+'/scripts/efficiency/OUTPUTS/plots/COIN_%s.png' % (ROOTPrefix.replace("replay_","")))

plt.figure(figsize=(12,8))

plt.subplot(141)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_10p6["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_3p8["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_4p9["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_6p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_8p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.ylabel('EDTM', fontsize=12)
plt.xlabel('Run Number', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(142)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["SHMS_Pion_SING_TRACK_EFF"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["SHMS_Pion_SING_TRACK_EFF"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["SHMS_Pion_SING_TRACK_EFF"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["SHMS_Pion_SING_TRACK_EFF"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["SHMS_Pion_SING_TRACK_EFF"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_10p6["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_3p8["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_4p9["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_6p2["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["SHMS_Pion_SING_TRACK_EFF"],yerr=efficiency_data_8p2["SHMS_Pion_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.ylabel('SHMS_Pion_SING_TRACK_EFF', fontsize=12)
plt.xlabel('Run Number', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(143)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["SHMS_Aero_SING_Pion_Eff"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["SHMS_Aero_SING_Pion_Eff"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["SHMS_Aero_SING_Pion_Eff"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["SHMS_Aero_SING_Pion_Eff"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["SHMS_Aero_SING_Pion_Eff"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_10p6["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_3p8["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_4p9["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_6p2["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["SHMS_Aero_SING_Pion_Eff"],yerr=efficiency_data_8p2["SHMS_Aero_SING_Pion_Eff_ERROR"],color='black',zorder=3)
plt.ylabel('SHMS_Aero_SING_Pion_Eff', fontsize=12)
plt.xlabel('Run Number', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(144)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["SHMS_Hodo_3_of_4_EFF"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["SHMS_Hodo_3_of_4_EFF"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["SHMS_Hodo_3_of_4_EFF"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["SHMS_Hodo_3_of_4_EFF"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["SHMS_Hodo_3_of_4_EFF"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
#plt.errorbar(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_10p6["SHMS_Hodo_3_of_4_EFF_ERROR"],color='blue',zorder=3)
#plt.errorbar(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_3p8["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_4p9["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_6p2["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["SHMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_8p2["SHMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
plt.ylabel('SHMS_Hodo_3_of_4_EFF', fontsize=12)
plt.xlabel('Run Number', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.tight_layout(rect=[0,0.03,1,0.95])   
plt.savefig(UTILPATH+'/scripts/efficiency/OUTPUTS/plots/SHMS_3-4_%s_run.png' % (ROOTPrefix.replace("replay_","")))

plt.figure(figsize=(12,8))

plt.subplot(141)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_10p6["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_3p8["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_4p9["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_6p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_8p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',zorder=3)
plt.ylabel('EDTM', fontsize=12)
plt.xlabel('Run Number', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(142)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["HMS_Elec_SING_TRACK_EFF"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["HMS_Elec_SING_TRACK_EFF"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["HMS_Elec_SING_TRACK_EFF"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["HMS_Elec_SING_TRACK_EFF"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["HMS_Elec_SING_TRACK_EFF"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_10p6["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_3p8["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_4p9["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_6p2["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["HMS_Elec_SING_TRACK_EFF"],yerr=efficiency_data_8p2["HMS_Elec_SING_TRACK_EFF_ERROR"],color='black',zorder=3)
plt.ylabel('HMS_Elec_SING_TRACK_EFF', fontsize=12)
plt.xlabel('Run Number', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(143)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["HMS_Cer_SING_Elec_Eff"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["HMS_Cer_SING_Elec_Eff"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["HMS_Cer_SING_Elec_Eff"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["HMS_Cer_SING_Elec_Eff"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["HMS_Cer_SING_Elec_Eff"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_10p6["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_3p8["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_4p9["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_6p2["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.errorbar(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["HMS_Cer_SING_Elec_Eff"],yerr=efficiency_data_8p2["HMS_Cer_SING_Elec_Eff_ERROR"],color='black',zorder=3)
plt.ylabel('HMS_Cer_SING_Elec_Eff', fontsize=12)
plt.xlabel('Run Number', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(144)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["HMS_Hodo_3_of_4_EFF"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["HMS_Hodo_3_of_4_EFF"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["HMS_Hodo_3_of_4_EFF"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["HMS_Hodo_3_of_4_EFF"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["HMS_Hodo_3_of_4_EFF"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
#plt.errorbar(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_10p6["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_3p8["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_4p9["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_6p2["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
#plt.errorbar(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["HMS_Hodo_3_of_4_EFF"],yerr=efficiency_data_8p2["HMS_Hodo_3_of_4_EFF_ERROR"],color='black',zorder=3)
plt.ylabel('HMS_Hodo_3_of_4_EFF', fontsize=12)
plt.xlabel('Run Number', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.tight_layout(rect=[0,0.03,1,0.95])   
plt.savefig(UTILPATH+'/scripts/efficiency/OUTPUTS/plots/HMS_EL-REAL_%s_run.png' % (ROOTPrefix.replace("replay_","")))

plt.figure(figsize=(12,8))

plt.subplot(141)    
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_10p6["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_3p8["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_4p9["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_6p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["Non_Scaler_EDTM_Live_Time"],yerr=efficiency_data_8p2["Non_Scaler_EDTM_Live_Time_ERROR"],color='black',linestyle='None',zorder=3)
plt.ylabel('EDTM', fontsize=12)
plt.xlabel('Run Number', fontsize=12)
plt.title('COIN %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(142)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["COIN_CPULT"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["COIN_CPULT"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["COIN_CPULT"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["COIN_CPULT"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["COIN_CPULT"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.errorbar(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["COIN_CPULT"],yerr=efficiency_data_10p6["COIN_CPULT_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["COIN_CPULT"],yerr=efficiency_data_3p8["COIN_CPULT_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["COIN_CPULT"],yerr=efficiency_data_4p9["COIN_CPULT_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["COIN_CPULT"],yerr=efficiency_data_6p2["COIN_CPULT_ERROR"],color='black',linestyle='None',zorder=3)
plt.errorbar(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["COIN_CPULT"],yerr=efficiency_data_8p2["COIN_CPULT_ERROR"],color='black',linestyle='None',zorder=3)

plt.ylabel('COIN CPULT', fontsize=12)
plt.xlabel('Run Number', fontsize=12)
plt.title('COIN %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(143)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["SHMS_3/4_Trigger_Rate"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["SHMS_3/4_Trigger_Rate"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["SHMS_3/4_Trigger_Rate"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["SHMS_3/4_Trigger_Rate"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["SHMS_3/4_Trigger_Rate"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.ylabel('SHMS 3/4 Trigger Rate [kHz]', fontsize=12)
plt.xlabel('Run Number', fontsize=12)
plt.title('SHMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.subplot(144)
plt.grid(zorder=1)
#plt.xlim(0,100)
#plt.ylim(0.9,1.1)
plt.scatter(efficiency_data_10p6["Run_Number"],efficiency_data_10p6["HMS_EL-REAL_Trigger_Rate"],color='blue',zorder=4,label='10p6')
plt.scatter(efficiency_data_3p8["Run_Number"],efficiency_data_3p8["HMS_EL-REAL_Trigger_Rate"],color='red',zorder=4,label='3p8')
plt.scatter(efficiency_data_4p9["Run_Number"],efficiency_data_4p9["HMS_EL-REAL_Trigger_Rate"],color='purple',zorder=4,label='4p9')
plt.scatter(efficiency_data_6p2["Run_Number"],efficiency_data_6p2["HMS_EL-REAL_Trigger_Rate"],color='orange',zorder=4,label='6p2')
plt.scatter(efficiency_data_8p2["Run_Number"],efficiency_data_8p2["HMS_EL-REAL_Trigger_Rate"],color='green',zorder=4,label='8p2')
plt.legend(loc="lower right", markerscale=0.7, scatterpoints=1, fontsize=10)
plt.ylabel('HMS EL-REAL Trigger Rate [kHz]', fontsize=12)
plt.xlabel('Run Number', fontsize=12)
plt.title('HMS %s-%s' % (int(min(efficiency_data["Run_Number"])),int(max(efficiency_data["Run_Number"]))), fontsize=12)

plt.tight_layout(rect=[0,0.03,1,0.95])
plt.savefig(UTILPATH+'/scripts/efficiency/OUTPUTS/plots/COIN_%s_run.png' % (ROOTPrefix.replace("replay_","")))


#plt.show()
