#! /usr/bin/python

# 21/05/21 - Muhammad Junaid, University of Regina, Canada

# Python version of the pion plotting script. Now utilises uproot to select event of each type and writes them to a root file.
# Python should allow for easier reading of databases storing diferent variables.

###################################################################################################################################################

# Import relevant packages
import uproot as up
import numpy as np
import root_numpy as rnp
import pandas as pd
import root_pandas as rpd
import ROOT
import scipy
import scipy.integrate as integrate
import matplotlib.pyplot as plt
import sys, math, os, subprocess
import array
sys.path.insert(0, 'python/')

##################################################################################################################################################

# Check the number of arguments provided to the script
if len(sys.argv)-1!=3:
    print("!!!!! ERROR !!!!!\n Expected 3 arguments\n Usage is with - ROOTfilePrefix RunNumber MaxEvents \n!!!!! ERROR !!!!!")
    sys.exit(1)

##################################################################################################################################################

# Input params - run number and max number of events
runNum = sys.argv[1]
MaxEvent = sys.argv[2]
ROOTPrefix = sys.argv[3]

USER = subprocess.getstatusoutput("whoami") # Grab user info for file finding
HOST = subprocess.getstatusoutput("hostname")

if ("farm" in HOST[1]):
#    REPLAYPATH = "/group/c-pionlt/USERS/%s/hallc_replay_lt" % USER[1]
    REPLAYPATH = "/group/c-kaonlt/USERS/%s/hallc_replay_lt" % USER[1]

elif ("qcd" in HOST[1]):
#    REPLAYPATH = "/group/c-pionlt/USERS/%s/hallc_replay_lt" % USER[1]
    REPLAYPATH = "/group/c-kaonlt/USERS/%s/hallc_replay_lt" % USER[1]

elif ("phys.uregina" in HOST[1]):
    REPLAYPATH = "/home/%s/work/JLab/hallc_replay_lt" % USER[1]

elif("skynet" in HOST[1]):
    REPLAYPATH = "/home/%s/Work/JLab/hallc_replay_lt" % USER[1]

#################################################################################################################################################

# Add more path setting as needed in a similar manner                                                                                                                                                          
OUTPATH = "%s/UTIL_PION/scripts/demo/OUTPUT/Analysis/PionLT" % REPLAYPATH        # Output folder location                                                                                                     
sys.path.insert(0, '%s/UTIL_PION/bin/python/' % REPLAYPATH)
import kaonlt as klt # Import kaonlt module, need the path setting line above prior to importing this                                                                                                         
print("Running as %s on %s, hallc_replay_lt path assumed as %s" % (USER[1], HOST[1], REPLAYPATH))

#################################################################################################################################################

# Construct the name of the rootfile based upon the info we provided
rootName = "%s/UTIL_PION//scripts/demo/OUTPUT/Analysis/PionLT/%s_%s_%s.root" % (REPLAYPATH, runNum, MaxEvent, ROOTPrefix)     # Input file location and variables taking
print ("Attempting to process %s" %(rootName))
if os.path.exists(OUTPATH):
    if os.path.islink(OUTPATH):
        pass
    elif os.path.isdir(OUTPATH):
        pass
    else:
        print ("%s exists but is not a directory or sym link, check your directory/link and try again" % (OUTPATH))
        sys.exit(2)
else:
    print("Output path not found, please make a sym link or directory called OUTPUT in UTIL_PION/scripts/demo to store output")
    sys.exit(3)
print ("Attempting to process %s" %(rootName))
if os.path.isfile(rootName):
    print ("%s exists, attempting to process" % (rootName))
else:
    print ("%s not found - do you have the correct sym link/folder set up?" % (rootName))
    sys.exit(4)
print("Output path checks out, outputting to %s" % (OUTPATH))

###############################################################################################################################################

# Read stuff from the main event tree
infile = ROOT.TFile.Open(rootName, "READ")
Uncut_Pion_Events_tree = infile.Get("Uncut_Pion_Events")
Cut_Pion_Events_All_tree = infile.Get("Cut_Pion_Events_All")
Cut_Pion_Events_Prompt_tree = infile.Get("Cut_Pion_Events_Prompt")
Cut_Pion_Events_Random_tree = infile.Get("Cut_Pion_Events_Random")

Uncut_Kaon_Events_tree = infile.Get("Uncut_Kaon_Events")
Cut_Kaon_Events_All_tree = infile.Get("Cut_Kaon_Events_All")
Cut_Kaon_Events_Prompt_tree = infile.Get("Cut_Kaon_Events_Prompt")
Cut_Kaon_Events_Random_tree = infile.Get("Cut_Kaon_Events_Random")

Uncut_Proton_Events_tree = infile.Get("Uncut_Proton_Events")
Cut_Proton_Events_All_tree = infile.Get("Cut_Proton_Events_All")
Cut_Proton_Events_Prompt_tree = infile.Get("Cut_Proton_Events_Prompt")
Cut_Proton_Events_Random_tree = infile.Get("Cut_Proton_Events_Random")

###############################################################################################################################################

# Defining Histograms for Pions
H_gtr_beta_pions_uncut = ROOT.TH1D("h1_H_gtr_beta_pions_uncut", "H_gtr_beta; HMS_#beta; Counts", 220, 0.6, 1.4)
H_gtr_xp_pions_uncut = ROOT.TH1D("h1_H_gtr_xp_pions_uncut", "H_gtr_xp; HMS_xp; Counts", 220, -0.6, 0.6)
H_gtr_yp_pions_uncut = ROOT.TH1D("h1_H_gtr_yp_pions_uncut", "H_gtr_yp; HMS_yp; Counts", 220, -0.6, 0.6)
H_gtr_dp_pions_uncut = ROOT.TH1D("h1_H_gtr_dp_pions_uncut", "H_gtr_dp; HMS_dp; Counts", 220, -40, 40)
H_hod_goodscinhit_pions_uncut = ROOT.TH1D("h1_H_hod_goodscinhit_pions_uncut", "H_hod_goodscinhit; HMS_hod_goodscinhi; Counts", 220, 0.6, 1.4)
H_hod_goodstarttime_pions_uncut = ROOT.TH1D("h1_H_hod_goodstarttime_pions_uncut", "H_hod_goodstarttime; HMS_hod_goodstarttime; Counts", 220, 0.6, 1.4)
H_cal_etotnorm_pions_uncut = ROOT.TH1D("h1_H_cal_etotnorm_pions_uncut", "H_cal_etotnorm; HMS_cal_etotnorm; Counts", 220, 0, 1.5)
H_cal_etottracknorm_pions_uncut = ROOT.TH1D("h1_H_cal_etottracknorm_pions_uncut", "H_cal_etottracknorm; HMS_cal_etottracknorm; Counts", 220, 0, 1.5)
H_cer_npeSum_pions_uncut = ROOT.TH1D("h1_H_cer_npeSum_pions_uncut", "H_cer_npeSum; HMS_cer_npeSum; Counts", 220, 0, 2)
H_RFTime_Dist_pions_uncut = ROOT.TH1D("h1_H_RFTime_Dist_pions_uncut", "H_RFTime_Dist; HMS_RFTime; Counts", 220, -1, 5)
P_gtr_beta_pions_uncut = ROOT.TH1D("h1_P_gtr_beta_pions_uncut", "P_gtr_beta; SHMS_#beta; Counts", 220, 0.5, 1.5)
P_gtr_xp_pions_uncut = ROOT.TH1D("h1_P_gtr_xp_pions_uncut", "P_gtr_xp; SHMS_xp; Counts", 220, -0.6, 0.6)
P_gtr_yp_pions_uncut = ROOT.TH1D("h1_P_gtr_yp_pions_uncut", "P_gtr_yp; SHMS_yp; Counts", 220, -0.8, 0.8)
P_gtr_dp_pions_uncut = ROOT.TH1D("h1_P_gtr_dp_pions_uncut", "P_gtr_dp; SHMS_dp; Counts", 220, -40, 40)
P_gtr_p_pions_uncut = ROOT.TH1D("h1_P_gtr_p_pions_uncut", "P_gtr_p; SHMS_p; Counts", 220, -5, 15)
P_hod_goodscinhit_pions_uncut = ROOT.TH1D("h1_P_hod_goodscinhit_pions_uncut", "P_hod_goodscinhit; SHMS_hod_goodscinhit; Counts", 220, 0.6, 1.6)
P_hod_goodstarttime_pions_uncut = ROOT.TH1D("h1_P_hod_goodstarttime_pions_uncut", "P_hod_goodstarttime; SHMS_hod_goodstarttime; Counts", 220, 0.6, 1.6)
P_cal_etotnorm_pions_uncut = ROOT.TH1D("h1_P_cal_etotnorm_pions_uncut", "P_cal_etotnorm; SHMS_cal_etotnorm; Counts", 220, 0, 1)
P_cal_etottracknorm_pions_uncut = ROOT.TH1D("h1_P_cal_etottracknorm_pions_uncut", "P_cal_etottracknorm; SHMS_cal_etottracknorm; Counts", 220, 0, 1)
P_hgcer_npeSum_pions_uncut = ROOT.TH1D("h1_P_hgcer_npeSum_pions_uncut", "P_hgcer_npeSum; SHMS_hgcer_npeSum; Counts", 220, 0, 0.5)
P_hgcer_xAtCer_pions_uncut = ROOT.TH1D("h1_P_hgcer_xAtCer_pions_uncut", "P_hgcer_xAtCer; SHMS_hgcer_xAtCer; Counts", 220, -10, 10)
P_hgcer_yAtCer_pions_uncut = ROOT.TH1D("h1_P_hgcer_yAtCer_pions_uncut", "P_hgcer_yAtCer; SHMS_hgcer_yAtCer; Counts", 220, -10, 10)
P_aero_npeSum_pions_uncut = ROOT.TH1D("h1_P_aero_npeSum_pions_uncut", "P_aero_npeSum; SHMS_aero_npeSum; Counts", 220, 0, 10)
P_aero_xAtAero_pions_uncut = ROOT.TH1D("h1_P_acero_xAtAero_pions_uncut", "P_aero_xAtAero; SHMS_aero_xAtAero; Counts", 220, -10, 10)
P_aero_yAtAero_pions_uncut = ROOT.TH1D("h1_P_aero_yAtAero_pions_uncut", "P_aero_yAtAero; SHMS_aero_yAtAero; Counts", 220, -10, 10)
P_kin_MMpi_pions_uncut = ROOT.TH1D("h1_P_kin_MMpi_pions_uncut", "P_kin_MMpi; MM_{#pi}; Counts", 220, 0, 2)
P_RFTime_Dist_pions_uncut = ROOT.TH1D("h1_P_RFTime_Dist_pions_uncut", "P_RFTime_Dist; SHMS_RFTime; Counts", 220, -1, 5)
CTime_ePiCoinTime_ROC1_pions_uncut = ROOT.TH1D("h1_CTime_ePiCoinTime_ROC1_pions_uncut", "CTime_ePiCoinTime_ROC1; e #pi Coin_Time; Counts", 220, -100, 100)
Q2_pions_uncut = ROOT.TH1D("h1_Q2_pions_uncut", "Q2; Q2; Counts", 220, -4, 10)
W_pions_uncut = ROOT.TH1D("h1_W_pions_uncut", "W; W; Counts", 220, -4, 10)
epsilon_pions_uncut = ROOT.TH1D("h1_epsilon_pions_uncut", "epsilon; epsilon; Counts", 220, -5, 5)

H_gtr_beta_pions_cut_all = ROOT.TH1D("h1_H_gtr_beta_pions_cut_all", "H_gtr_beta; HMS_#beta; Counts", 220, 0.5, 1.5)
H_gtr_xp_pions_cut_all = ROOT.TH1D("h1_H_gtr_xp_pions_cut_all", "H_gtr_xp; HMS_xp; Counts", 220, -0.6, 0.6)
H_gtr_yp_pions_cut_all = ROOT.TH1D("h1_H_gtr_yp_pions_cut_all", "H_gtr_yp; HMS_yp; Counts", 220, -0.6, 0.6)
H_gtr_dp_pions_cut_all = ROOT.TH1D("h1_H_gtr_dp_pions_cut_all", "H_gtr_dp; HMS_dp; Counts", 220, -15, 15)
H_hod_goodscinhit_pions_cut_all = ROOT.TH1D("h1_H_hod_goodscinhit_pions_cut_all", "H_hod_goodscinhit; HMS_hod_goodscinhit; Counts", 220, 0.5, 1.5)
H_hod_goodstarttime_pions_cut_all = ROOT.TH1D("h1_H_hod_goodstarttime_pions_cut_all", "H_hod_goodstarttime; HMS_hod_goodstarttime; Counts", 220, 0.5, 1.5)
H_cal_etotnorm_pions_cut_all = ROOT.TH1D("h1_H_cal_etotnorm_pions_cut_all", "H_cal_etotnorm; HMS_cal_etotnorm; Counts", 220, 0, 2)
H_cal_etottracknorm_pions_cut_all = ROOT.TH1D("h1_H_cal_etottracknorm_pions_cut_all", "H_cal_etottracknorm; HMS_cal_etottracknorm; Counts", 220, 0, 2)
H_cer_npeSum_pions_cut_all = ROOT.TH1D("h1_H_cer_npeSum_pions_cut_all", "H_cer_npeSum; HMS_cer_npeSum; Counts", 220, 0, 20)
H_RFTime_Dist_pions_cut_all = ROOT.TH1D("h1_H_RFTime_Dist_pions_cut_all", "H_RFTime_Dist; HMS_RFTime; Counts", 220, -1, 5)
P_gtr_beta_pions_cut_all = ROOT.TH1D("h1_P_gtr_beta_pions_cut_all", "P_gtr_beta; SHMS_#beta; Counts", 220, 0, 2)
P_gtr_xp_pions_cut_all = ROOT.TH1D("h1_P_gtr_xp_pions_cut_all", "P_gtr_xp; SHMS_xp; Counts", 220, -0.6, 0.6)
P_gtr_yp_pions_cut_all = ROOT.TH1D("h1_P_gtr_yp_pions_cut_all", "P_gtr_yp; SHMS_yp; Counts", 220, -0.6, 0.6)
P_gtr_dp_pions_cut_all = ROOT.TH1D("h1_P_gtr_dp_pions_cut_all", "P_gtr_dp; SHMS_dp; Counts", 220, -20, 20)
P_gtr_p_pions_cut_all = ROOT.TH1D("h1_P_gtr_p_pions_cut_all", "P_gtr_p; SHMS_p; Counts", 220, 0, 12)
P_hod_goodscinhit_pions_cut_all = ROOT.TH1D("h1_P_hod_goodscinhit_pions_cut_all", "P_hod_goodscinhit; SHMS_hod_goodscinhit; Counts", 220, 0.6, 1.4)
P_hod_goodstarttime_pions_cut_all = ROOT.TH1D("h1_P_hod_goodstarttime_pions_cut_all", "P_hod_goodstarttime; SHMS_hod_goodstarttime; Counts", 220, 0.6, 1.4)
P_cal_etotnorm_pions_cut_all = ROOT.TH1D("h1_P_cal_etotnorm_pions_cut_all", "P_cal_etotnorm; SHMS_cal_etotnorm; Counts", 220, 0, 1.4)
P_cal_etottracknorm_pions_cut_all = ROOT.TH1D("h1_P_cal_etottracknorm_pions_cut_all", "P_cal_etottracknorm; SHMS_cal_etottracknorm; Counts", 220, 0, 1.4)
P_hgcer_npeSum_pions_cut_all = ROOT.TH1D("h1_P_hgcer_npeSum_pions_cut_all", "P_hgcer_npeSum; SHMS_hgcer_npeSum; Counts", 220, -10, 50)
P_hgcer_xAtCer_pions_cut_all = ROOT.TH1D("h1_P_hgcer_xAtCer_pions_cut_all", "P_hgcer_xAtCer; SHMS_hgcer_xAtCer; Counts", 220, -40, 40)
P_hgcer_yAtCer_pions_cut_all = ROOT.TH1D("h1_P_hgcer_yAtCer_pions_cut_all", "P_hgcer_yAtCer; SHMS_hgcer_yAtCer; Counts", 220, -40, 40)
P_aero_npeSum_pions_cut_all = ROOT.TH1D("h1_P_aero_npeSum_pions_cut_all", "P_aero_npeSum; SHMS_aero_npeSum; Counts", 220, 1, 50)
P_aero_xAtAero_pions_cut_all = ROOT.TH1D("h1_P_acero_xAtAero_pions_cut_all", "P_aero_xAtAero; SHMS_aero_xAtAero; Counts", 220, -40, 40)
P_aero_yAtAero_pions_cut_all = ROOT.TH1D("h1_P_aero_yAtAero_pions_cut_all", "P_aero_yAtAero; SHMS_aero_yAtAero; Counts", 220, -40, 40)
P_kin_MMpi_pions_cut_all = ROOT.TH1D("h1_P_kin_MMpi_pions_cut_all", "P_kin_MMpi; MM_{#pi}; Counts", 220, 0.5, 1.8)
P_RFTime_Dist_pions_cut_all = ROOT.TH1D("h1_P_RFTime_Dist_pions_cut_all", "P_RFTime_Dist; SHMS_RFTime; Counts", 220, -1, 5)
CTime_ePiCoinTime_ROC1_pions_cut_all = ROOT.TH1D("h1_CTime_ePiCoinTime_ROC1_pions_cut_all", "CTime_ePiCoinTime_ROC1; e #pi Coin_Time; Counts", 220, -50, 50)
Q2_pions_cut_all = ROOT.TH1D("h1_Q2_pions_cut_all", "Q2; Q2; Counts", 220, -4, 10)
W_pions_cut_all = ROOT.TH1D("h1_W_pions_cut_all", "W; W; Counts", 220, -2, 8)
epsilon_pions_cut_all = ROOT.TH1D("h1_epsilon_pions_cut_all", "epsilon; epsilon; Counts", 220, -1, 2)

P_gtr_beta_pions_cut_prompt = ROOT.TH1D("h1_P_gtr_beta_pions_cut_prompt", "P_gtr_beta; SHMS_#beta; Counts", 220, 0.6, 1.4)
P_RFTime_Dist_pions_cut_prompt = ROOT.TH1D("h1_P_RFTime_Dist_pions_cut_prompt", "P_RFTime_Dist; SHMS_RFTime; Counts", 220, 0, 4)
CTime_ePiCoinTime_ROC1_pions_cut_prompt = ROOT.TH1D("h1_CTime_ePiCoinTime_ROC1_pions_cut_prompt", "CTime_ePiCoinTime_ROC1; e #pi Coin_Time; Counts", 220, -8, 8)
P_kin_MMpi_pions_cut_prompt = ROOT.TH1D("h1_P_kin_MMpi_pions_cut_prompt", "P_kin_MMpi; MM_{#pi}; Counts", 220, 0.5, 1.8)

P_gtr_beta_pions_cut_random = ROOT.TH1D("h1_P_gtr_beta_pions_cut_random", "P_gtr_beta; SHMS_#beta; Counts", 220, 0.6, 1.4)
P_RFTime_Dist_pions_cut_random = ROOT.TH1D("h1_P_RFTime_Dist_pions_cut_random", "P_RFTime_Dist; SHMS_RFTime; Counts", 220, -1, 5)
CTime_ePiCoinTime_ROC1_pions_cut_random = ROOT.TH1D("h1_CTime_ePiCoinTime_ROC1_pions_cut_random", "CTime_ePiCoinTime_ROC1; e #pi Coin_Time; Counts", 220, -40, 40)
P_kin_MMpi_pions_cut_random = ROOT.TH1D("h1_P_kin_MMpi_pions_cut_random", "P_kin_MMpi; MM_{#pi}; Counts", 220, 0.5, 1.8)

CTime_ePiCoinTime_ROC1_pions_cut_random_scaled = ROOT.TH1D("h1_CTime_ePiCoinTime_ROC1_pions_cut_random_scaled", "CTime_ePiCoinTime_ROC1; e #pi Coin_Time; Counts", 220, -40, 40)
CTime_ePiCoinTime_ROC1_pions_cut_random_sub = ROOT.TH1D("h1_CTime_ePiCoinTime_ROC1_pions_cut_random_sub", "CTime_ePiCoinTime_ROC1; e #pi Coin_Time; Counts", 220, -8, 8)
P_kin_MMpi_pions_cut_random_scaled = ROOT.TH1D("h1_P_kin_MMpi_pions_cut_random_scaled", "P_kin_MMpi; MM_{#pi}; Counts", 220, 0.5, 1.8)
P_kin_MMpi_pions_cut_random_sub = ROOT.TH1D("h1_P_kin_MMpi_pions_cut_random_sub", "P_kin_MMpi; MM_{#pi}; Counts", 220, 0.5, 1.8)

##############################################################################################################################################

# Defining Histograms for Kaons
H_gtr_beta_kaons_uncut = ROOT.TH1D("h1_H_gtr_beta_kaons_uncut", "H_gtr_beta; HMS_#beta; Counts", 220, 0.6, 1.4)
H_gtr_xp_kaons_uncut = ROOT.TH1D("h1_H_gtr_xp_kaons_uncut", "H_gtr_xp; HMS_xp; Counts", 220, -0.6, 0.6)
H_gtr_yp_kaons_uncut = ROOT.TH1D("h1_H_gtr_yp_kaons_uncut", "H_gtr_yp; HMS_yp; Counts", 220, -0.6, 0.6)
H_gtr_dp_kaons_uncut = ROOT.TH1D("h1_H_gtr_dp_kaons_uncut", "H_gtr_dp; HMS_dp; Counts", 220, -40, 40)
H_hod_goodscinhit_kaons_uncut = ROOT.TH1D("h1_H_hod_goodscinhit_kaons_uncut", "H_hod_goodscinhit; HMS_hod_goodscinhit; Counts", 220, 0.6, 1.4)
H_hod_goodstarttime_kaons_uncut = ROOT.TH1D("h1_H_hod_goodstarttime_kaons_uncut", "H_hod_goodstarttime; HMS_hod_goodstarttime; Counts", 220, 0.6, 1.4)
H_cal_etotnorm_kaons_uncut = ROOT.TH1D("h1_H_cal_etotnorm_kaons_uncut", "H_cal_etotnorm; HMS_cal_etotnorm; Counts", 220, 0, 2)
H_cal_etottracknorm_kaons_uncut = ROOT.TH1D("h1_H_cal_etottracknorm_kaons_uncut", "H_cal_etottracknorm; HMS_cal_etottracknorm; Counts", 220, 0, 2)
H_cer_npeSum_kaons_uncut = ROOT.TH1D("h1_H_cer_npeSum_kaons_uncut", "H_cer_npeSum; HMS_cer_npeSum; Counts", 220, 0, 2)
H_RFTime_Dist_kaons_uncut = ROOT.TH1D("h1_H_RFTime_Dist_kaons_uncut", "H_RFTime_Dist; HMS_RFTime; Counts", 220, -1, 5)
P_gtr_beta_kaons_uncut = ROOT.TH1D("h1_P_gtr_beta_kaons_uncut", "P_gtr_beta; SHMS_#beta; Counts", 220, 0.6, 1.6)
P_gtr_xp_kaons_uncut = ROOT.TH1D("h1_P_gtr_xp_kaons_uncut", "P_gtr_xp; SHMS_xp; Counts", 220, -0.6, 0.6)
P_gtr_yp_kaons_uncut = ROOT.TH1D("h1_P_gtr_yp_kaons_uncut", "P_gtr_yp; SHMS_yp; Counts", 220, -0.8, 0.8)
P_gtr_dp_kaons_uncut = ROOT.TH1D("h1_P_gtr_dp_kaons_uncut", "P_gtr_dp; SHMS_dp; Counts", 220, -40, 40)
P_gtr_p_kaons_uncut = ROOT.TH1D("h1_P_gtr_p_kaons_uncut", "P_gtr_p; SHMS_p; Counts", 220, -2, 14)
P_hod_goodscinhit_kaons_uncut = ROOT.TH1D("h1_P_hod_goodscinhit_kaons_uncut", "P_hod_goodscinhit; SHMS_hod_goodscinhit; Counts", 220, 0.6, 1.4)
P_hod_goodstarttime_kaons_uncut = ROOT.TH1D("h1_P_hod_goodstarttime_kaons_uncut", "P_hod_goodstarttime; SHMS_hod_goodstarttime; Counts", 220, 0.6, 1.4)
P_cal_etotnorm_kaons_uncut = ROOT.TH1D("h1_P_cal_etotnorm_kaons_uncut", "P_cal_etotnorm; SHMS_cal_etotnorm; Counts", 220, 0, 1.6)
P_cal_etottracknorm_kaons_uncut = ROOT.TH1D("h1_P_cal_etottracknorm_kaons_uncut", "P_cal_etottracknorm; SHMS_cal_etottracknorm; Counts", 220, 0, 1.6)
P_hgcer_npeSum_kaons_uncut = ROOT.TH1D("h1_P_hgcer_npeSum_kaons_uncut", "P_hgcer_npeSum; SHMS_hgcer_npeSum; Counts", 220, 0, 0.5)
P_hgcer_xAtCer_kaons_uncut = ROOT.TH1D("h1_P_hgcer_xAtCer_kaons_uncut", "P_hgcer_xAtCer; SHMS_hgcer_xAtCer; Counts", 220, -10, 10)
P_hgcer_yAtCer_kaons_uncut = ROOT.TH1D("h1_P_hgcer_yAtCer_kaons_uncut", "P_hgcer_yAtCer; SHMS_hgcer_yAtCer; Counts", 220, -10, 10)
P_aero_npeSum_kaons_uncut = ROOT.TH1D("h1_P_aero_npeSum_kaons_uncut", "P_aero_npeSum; SHMS_aero_npeSum; Counts", 220, 0, 10)
P_aero_xAtAero_kaons_uncut = ROOT.TH1D("h1_P_acero_xAtAero_kaons_uncut", "P_aero_xAtAero; SHMS_aero_xAtAero; Counts", 220, -10, 10)
P_aero_yAtAero_kaons_uncut = ROOT.TH1D("h1_P_aero_yAtAero_kaons_uncut", "P_aero_yAtAero; SHMS_aero_yAtAero; Counts", 220, -10, 10)
P_kin_MMK_kaons_uncut = ROOT.TH1D("h1_P_kin_MMK_kaons_uncut", "P_kin_MMK; MM_{K}; Counts", 220, 0, 2)
P_RFTime_Dist_kaons_uncut = ROOT.TH1D("h1_P_RFTime_Dist_kaons_uncut", "P_RFTime_Dist; SHMS_RFTime", 220, -1, 5)
CTime_eKCoinTime_ROC1_kaons_uncut = ROOT.TH1D("h1_CTime_eKCoinTime_ROC1_kaons_uncut", "CTime_eKCoinTime_ROC1; e K Coin_Time; Counts", 220, -100, 100)
Q2_kaons_uncut = ROOT.TH1D("h1_Q2_kaons_uncut", "Q2; Q2; Counts", 220, -4, 10)
W_kaons_uncut = ROOT.TH1D("h1_W_kaons_uncut", "W; W; Counts", 220, -4, 10)
epsilon_kaons_uncut = ROOT.TH1D("h1_epsilon_kaons_uncut", "epsilon; epsilon; Counts", 220, -8, 10)

H_gtr_beta_kaons_cut_all = ROOT.TH1D("h1_H_gtr_beta_kaons_cut_all", "H_gtr_beta; HMS_#beta; Counts", 220, 0.6, 1.4)
H_gtr_xp_kaons_cut_all = ROOT.TH1D("h1_H_gtr_xp_kaons_cut_all", "H_gtr_xp; HMS_xp; Counts", 220, -0.6, 0.6)
H_gtr_yp_kaons_cut_all = ROOT.TH1D("h1_H_gtr_yp_kaons_cut_all", "H_gtr_yp; HMS_yp; Counts", 220, -0.6, 0.6)
H_gtr_dp_kaons_cut_all = ROOT.TH1D("h1_H_gtr_dp_kaons_cut_all", "H_gtr_dp; HMS_dp; Counts", 220, -15, 15)
H_hod_goodscinhit_kaons_cut_all = ROOT.TH1D("h1_H_hod_goodscinhit_kaons_cut_all", "H_hod_goodscinhit; HMS_hod_goodscinhit; Counts", 220, 0.6, 1.4)
H_hod_goodstarttime_kaons_cut_all = ROOT.TH1D("h1_H_hod_goodstarttime_kaons_cut_all", "H_hod_goodstarttime; HMS_hod_goodstarttime; Counts", 220, 0.6, 1.4)
H_cal_etotnorm_kaons_cut_all = ROOT.TH1D("h1_H_cal_etotnorm_kaons_cut_all", "H_cal_etotnorm; HMS_cal_etotnorm; Counts", 220, 0, 2)
H_cal_etottracknorm_kaons_cut_all = ROOT.TH1D("h1_H_cal_etottracknorm_kaons_cut_all", "H_cal_etottracknorm; HMS_cal_etottracknorm; Counts", 220, 0, 2)
H_cer_npeSum_kaons_cut_all = ROOT.TH1D("h1_H_cer_npeSum_kaons_cut_all", "H_cer_npeSum; HMS_cer_npeSum; Counts", 220, 0, 20)
H_RFTime_Dist_kaons_cut_all = ROOT.TH1D("h1_H_RFTime_Dist_kaons_cut_all", "H_RFTime_Dist; HMS_RFTime; Counts", 220, -1, 5)
P_gtr_beta_kaons_cut_all = ROOT.TH1D("h1_P_gtr_beta_kaons_cut_all", "P_gtr_beta; SHMS_#beta; Counts", 220, 0.4, 1.6)
P_gtr_xp_kaons_cut_all = ROOT.TH1D("h1_P_gtr_xp_kaons_cut_all", "P_gtr_xp; SHMS_xp; Counts", 220, -0.6, 0.6)
P_gtr_yp_kaons_cut_all = ROOT.TH1D("h1_P_gtr_yp_kaons_cut_all", "P_gtr_yp; SHMS_yp; Counts", 220, -0.6, 0.6)
P_gtr_dp_kaons_cut_all = ROOT.TH1D("h1_P_gtr_dp_kaons_cut_all", "P_gtr_dp; SHMS_dp; Counts", 220, -20, 20)
P_gtr_p_kaons_cut_all = ROOT.TH1D("h1_P_gtr_p_kaons_cut_all", "P_gtr_p; SHMS_p; Counts", 220, 4, 8)
P_hod_goodscinhit_kaons_cut_all = ROOT.TH1D("h1_P_hod_goodscinhit_kaons_cut_all", "P_hod_goodscinhit; SHMS_hod_goodscinhit; Counts", 220, 0.6, 1.4)
P_hod_goodstarttime_kaons_cut_all = ROOT.TH1D("h1_P_hod_goodstarttime_kaons_cut_all", "P_hod_goodstarttime; SHMS_hod_goodstarttime; Counts", 220, 0.6, 1.4)
P_cal_etotnorm_kaons_cut_all = ROOT.TH1D("h1_P_cal_etotnorm_kaons_cut_all", "P_cal_etotnorm; SHMS_cal_etotnorm; Counts", 220, 0, 1.4)
P_cal_etottracknorm_kaons_cut_all = ROOT.TH1D("h1_P_cal_etottracknorm_kaons_cut_all", "P_cal_etottracknorm; SHMS_cal_etottracknorm; Counts", 220, 0, 1.4)
P_hgcer_npeSum_kaons_cut_all = ROOT.TH1D("h1_P_hgcer_npeSum_kaons_cut_all", "P_hgcer_npeSum; SHMS_hgcer_npeSum; Counts", 220, 0, 0.5)
P_hgcer_xAtCer_kaons_cut_all = ROOT.TH1D("h1_P_hgcer_xAtCer_kaons_cut_all", "P_hgcer_xAtCer; SHMS_hgcer_xAtCer; Counts", 220, -40, 40)
P_hgcer_yAtCer_kaons_cut_all = ROOT.TH1D("h1_P_hgcer_yAtCer_kaons_cut_all", "P_hgcer_yAtCer; SHMS_hgcer_yAtCer; Counts", 220, -40, 40)
P_aero_npeSum_kaons_cut_all = ROOT.TH1D("h1_P_aero_npeSum_kaons_cut_all", "P_aero_npeSum; SHMS_aero_npeSum; Counts", 220, 1, 50)
P_aero_xAtAero_kaons_cut_all = ROOT.TH1D("h1_P_acero_xAtAero_kaons_cut_all", "P_aero_xAtAero; SHMS_aero_xAtAero; Counts", 220, -40, 40)
P_aero_yAtAero_kaons_cut_all = ROOT.TH1D("h1_P_aero_yAtAero_kaons_cut_all", "P_aero_yAtAero; SHMS_aero_yAtAero; Counts", 220, -40, 40)
P_kin_MMK_kaons_cut_all = ROOT.TH1D("h1_P_kin_MMK_kaons_cut_all", "P_kin_MMK; MM_{K}; Counts", 220, 0.5, 1.8)
P_RFTime_Dist_kaons_cut_all = ROOT.TH1D("h1_P_RFTime_Dist_kaons_cut_all", "P_RFTime_Dist; SHMS_RFTime; Counts", 220, -1, 5)
CTime_eKCoinTime_ROC1_kaons_cut_all = ROOT.TH1D("h1_CTime_eKCoinTime_ROC1_kaons_cut_all", "CTime_eKCoinTime_ROC1; e K Coin_Time; Counts", 220, -50, 50)
Q2_kaons_cut_all = ROOT.TH1D("h1_Q2_kaons_cut_all", "Q2; Q2; Counts", 220, -4, 10)
W_kaons_cut_all = ROOT.TH1D("h1_W_kaons_cut_all", "W; W; Counts", 220, -2, 8)
epsilon_kaons_cut_all = ROOT.TH1D("h1_epsilon_kaons_cut_all", "epsilon; epsilon; Counts", 220, -4, 4)

P_gtr_beta_kaons_cut_prompt = ROOT.TH1D("h1_P_gtr_beta_kaons_cut_prompt", "P_gtr_beta; SHMS_#beta; Counts", 220, 0.6, 1.4)
P_RFTime_Dist_kaons_cut_prompt = ROOT.TH1D("h1_P_RFTime_Dist_kaons_cut_prompt", "P_RFTime_Dist; SHMS_RFTime; Counts", 220, -1, 5)
CTime_eKCoinTime_ROC1_kaons_cut_prompt = ROOT.TH1D("h1_CTime_eKCoinTime_ROC1_kaons_cut_prompt", "CTime_eKCoinTime_ROC1; e K Coin_Time; Counts", 220, -8, 8)
P_kin_MMK_kaons_cut_prompt = ROOT.TH1D("h1_P_kin_MMK_kaons_cut_prompt", "P_kin_MMK; MM_{K}; Counts", 220, 0.5, 1.8)

P_gtr_beta_kaons_cut_random = ROOT.TH1D("h1_P_gtr_beta_kaons_cut_random", "P_gtr_beta; SHMS_#beta; Counts", 220, 0.6, 1.4)
P_RFTime_Dist_kaons_cut_random = ROOT.TH1D("h1_P_RFTime_Dist_kaons_cut_random", "P_RFTime_Dist; SHMS_RFTime; Counts", 220, -1, 5)
CTime_eKCoinTime_ROC1_kaons_cut_random = ROOT.TH1D("h1_CTime_eKCoinTime_ROC1_kaons_cut_random", "CTime_eKCoinTime_ROC1; e K Coin_Time; Counts", 220, -40, 40)
P_kin_MMK_kaons_cut_random = ROOT.TH1D("h1_P_kin_MMK_kaons_cut_random", "P_kin_MMK; MM_{K}; Counts", 220, 0.5, 1.8)

CTime_eKCoinTime_ROC1_kaons_cut_random_scaled = ROOT.TH1D("h1_CTime_eKCoinTime_ROC1_kaons_cut_random_scaled", "CTime_eKCoinTime_ROC1; e K Coin_Time; Counts", 220, -40, 40)
CTime_eKCoinTime_ROC1_kaons_cut_random_sub = ROOT.TH1D("h1_CTime_eKCoinTime_ROC1_kaons_cut_random_sub", "CTime_eKCoinTime_ROC1; e K Coin_Time; Counts", 220, -8, 8)
P_kin_MMK_kaons_cut_random_scaled = ROOT.TH1D("h1_P_kin_MMK_kaons_cut_random_scaled", "P_kin_MMK; MM_{K}; Counts", 220, 0.5, 1.8)
P_kin_MMK_kaons_cut_random_sub = ROOT.TH1D("h1_P_kin_MMK_kaons_cut_random_sub", "P_kin_MMK; MM_{K}; Counts", 220, 0.5, 1.8)

###############################################################################################################################################

# Defining Histograms for Protons
H_gtr_beta_protons_uncut = ROOT.TH1D("h1_H_gtr_beta_protons_uncut", "H_gtr_beta; HMS_#beta; Counts", 220, 0.6, 1.4)
H_gtr_xp_protons_uncut = ROOT.TH1D("h1_H_gtr_xp_protons_uncut", "H_gtr_xp; HMS_xp; Counts", 220, -0.6, 0.6)
H_gtr_yp_protons_uncut = ROOT.TH1D("h1_H_gtr_yp_protons_uncut", "H_gtr_yp; HMS_yp; Counts", 220, -0.6, 0.6)
H_gtr_dp_protons_uncut = ROOT.TH1D("h1_H_gtr_dp_protons_uncut", "H_gtr_dp; HMS_dp; Counts", 220, -40, 40)
H_hod_goodscinhit_protons_uncut = ROOT.TH1D("h1_H_hod_goodscinhit_protons_uncut", "H_hod_goodscinhit; HMS_hod_goodscinhit; Counts", 220, 0.6, 1.4)
H_hod_goodstarttime_protons_uncut = ROOT.TH1D("h1_H_hod_goodstarttime_protons_uncut", "H_hod_goodstarttime; HMS_hod_goodstarttime; Counts", 220, 0.6, 1.4)
H_cal_etotnorm_protons_uncut = ROOT.TH1D("h1_H_cal_etotnorm_protons_uncut", "H_cal_etotnorm; HMS_cal_etotnorm; Counts", 220, 0, 2)
H_cal_etottracknorm_protons_uncut = ROOT.TH1D("h1_H_cal_etottracknorm_protons_uncut", "H_cal_etottracknorm; HMS_cal_etottracknorm; Counts", 220, 0, 2)
H_cer_npeSum_protons_uncut = ROOT.TH1D("h1_H_cer_npeSum_protons_uncut", "H_cer_npeSum; HMS_cer_npeSum; Counts", 220, 0, 2)
H_RFTime_Dist_protons_uncut = ROOT.TH1D("h1_H_RFTime_Dist_protons_uncut", "H_RFTime_Dist; HMS_RFTime; Counts", 220, -1, 5)
P_gtr_beta_protons_uncut = ROOT.TH1D("h1_P_gtr_beta_protons_uncut", "P_gtr_beta; SHMS_#beta; Counts", 220, 0.6, 1.4)
P_gtr_xp_protons_uncut = ROOT.TH1D("h1_P_gtr_xp_protons_uncut", "P_gtr_xp; SHMS_xp; Counts", 220, -0.6, 0.6)
P_gtr_yp_protons_uncut = ROOT.TH1D("h1_P_gtr_yp_protons_uncut", "P_gtr_yp; SHMS_yp; Counts", 220, -0.8, 0.8)
P_gtr_dp_protons_uncut = ROOT.TH1D("h1_P_gtr_dp_protons_uncut", "P_gtr_dp; SHMS_dp; Counts", 220, -50, 50)
P_gtr_p_protons_uncut = ROOT.TH1D("h1_P_gtr_p_protons_uncut", "P_gtr_p; SHMS_p; Counts", 220, -10, 20)
P_hod_goodscinhit_protons_uncut = ROOT.TH1D("h1_P_hod_goodscinhit_protons_uncut", "P_hod_goodscinhit; SHMS_hod_goodscinhit; Counts", 220, 0.6, 1.4)
P_hod_goodstarttime_protons_uncut = ROOT.TH1D("h1_P_hod_goodstarttime_protons_uncut", "P_hod_goodstarttime; SHMS_hod_goodstarttime; Counts", 220, 0.6, 1.4)
P_cal_etotnorm_protons_uncut = ROOT.TH1D("h1_P_cal_etotnorm_protons_uncut", "P_cal_etotnorm; SHMS_cal_etotnorm; Counts", 220, 0, 1.6)
P_cal_etottracknorm_protons_uncut = ROOT.TH1D("h1_P_cal_etottracknorm_protons_uncut", "P_cal_etottracknorm; SHMS_cal_etottracknorm; Counts", 220, 0, 1.6)
P_hgcer_npeSum_protons_uncut = ROOT.TH1D("h1_P_hgcer_npeSum_protons_uncut", "P_hgcer_npeSum; SHMS_hgcer_npeSum; Counts", 220, 0, 0.5)
P_hgcer_xAtCer_protons_uncut = ROOT.TH1D("h1_P_hgcer_xAtCer_protons_uncut", "P_hgcer_xAtCer; SHMS_hgcer_xAtCer; Counts", 220, -10, 10)
P_hgcer_yAtCer_protons_uncut = ROOT.TH1D("h1_P_hgcer_yAtCer_protons_uncut", "P_hgcer_yAtCer; SHMS_hgcer_yAtCer; Counts", 220, -10, 10)
P_aero_npeSum_protons_uncut = ROOT.TH1D("h1_P_aero_npeSum_protons_uncut", "P_aero_npeSum; SHMS_aero_npeSum; Counts", 220, 0, 10)
P_aero_xAtAero_protons_uncut = ROOT.TH1D("h1_P_acero_xAtAero_protons_uncut", "P_aero_xAtAero; SHMS_aero_xAtAero; Counts", 220, -10, 10)
P_aero_yAtAero_protons_uncut = ROOT.TH1D("h1_P_aero_yAtAero_protons_uncut", "P_aero_yAtAero; SHMS_aero_yAtAero; Counts", 220, -10, 10)
P_kin_MMp_protons_uncut = ROOT.TH1D("h1_P_kin_MMp_protons_uncut", "P_kin_MMp; MM_{p}; Counts", 220, 0, 2)
P_RFTime_Dist_protons_uncut = ROOT.TH1D("h1_P_RFTime_Dist_protons_uncut", "P_RFTime_Dist; SHMS_RFTime; Counts", 220, -1, 5)
CTime_epCoinTime_ROC1_protons_uncut = ROOT.TH1D("h1_CTime_epCoinTime_ROC1_protons_uncut", "CTime_epCoinTime_ROC1; e p Coin_Time; Counts", 220, -100, 100)
Q2_protons_uncut = ROOT.TH1D("h1_Q2_protons_uncut", "Q2; Q2; Counts", 220, -4, 10)
W_protons_uncut = ROOT.TH1D("h1_W_protons_uncut", "W; W; Counts", 220, -4, 10)
epsilon_protons_uncut = ROOT.TH1D("h1_epsilon_protons_uncut", "epsilon; epsilon; Counts", 220, -6, 6)

H_gtr_beta_protons_cut_all = ROOT.TH1D("h1_H_gtr_beta_protons_cut_all", "H_gtr_beta; HMS_#beta; Counts", 220, 0.6, 1.4)
H_gtr_xp_protons_cut_all = ROOT.TH1D("h1_H_gtr_xp_protons_cut_all", "H_gtr_xp; HMS_xp; Counts", 220, -0.6, 0.6)
H_gtr_yp_protons_cut_all = ROOT.TH1D("h1_H_gtr_yp_protons_cut_all", "H_gtr_yp; HMS_yp; Counts", 220, -0.6, 0.6)
H_gtr_dp_protons_cut_all = ROOT.TH1D("h1_H_gtr_dp_protons_cut_all", "H_gtr_dp; HMS_dp; Counts", 220, -15, 15)
H_hod_goodscinhit_protons_cut_all = ROOT.TH1D("h1_H_hod_goodscinhit_protons_cut_all", "H_hod_goodscinhit; HMS_hod_goodscinhit; Counts", 220, 0.6, 1.4)
H_hod_goodstarttime_protons_cut_all = ROOT.TH1D("h1_H_hod_goodstarttime_protons_cut_all", "H_hod_goodstarttime; HMS_hod_goodstarttime; Counts", 220, 0.6, 1.4)
H_cal_etotnorm_protons_cut_all = ROOT.TH1D("h1_H_cal_etotnorm_protons_cut_all", "H_cal_etotnorm; HMS_cal_etotnorm; Counts", 220, 0, 2)
H_cal_etottracknorm_protons_cut_all = ROOT.TH1D("h1_H_cal_etottracknorm_protons_cut_all", "H_cal_etottracknorm; HMS_cal_etottracknorm; Counts", 220, 0, 2)
H_cer_npeSum_protons_cut_all = ROOT.TH1D("h1_H_cer_npeSum_protons_cut_all", "H_cer_npeSum; HMS_cer_npeSum; Counts", 220, 0, 20)
H_RFTime_Dist_protons_cut_all = ROOT.TH1D("h1_H_RFTime_Dist_protons_cut_all", "H_RFTime_Dist; HMS_RFTime; Counts", 220, -1, 5)
P_gtr_beta_protons_cut_all = ROOT.TH1D("h1_P_gtr_beta_protons_cut_all", "P_gtr_beta; SHMS_#beta; Counts", 220, 0.6, 1.4)
P_gtr_xp_protons_cut_all = ROOT.TH1D("h1_P_gtr_xp_protons_cut_all", "P_gtr_xp; SHMS_xp; Counts", 220, -0.6, 0.6)
P_gtr_yp_protons_cut_all = ROOT.TH1D("h1_P_gtr_yp_protons_cut_all", "P_gtr_yp; SHMS_yp; Counts", 220, -0.6, 0.6)
P_gtr_dp_protons_cut_all = ROOT.TH1D("h1_P_gtr_dp_protons_cut_all", "P_gtr_dp; SHMS_dp; Counts", 220, -20, 20)
P_gtr_p_protons_cut_all = ROOT.TH1D("h1_P_gtr_p_protons_cut_all", "P_gtr_p; SHMS_p; Counts", 220, 0, 12)
P_hod_goodscinhit_protons_cut_all = ROOT.TH1D("h1_P_hod_goodscinhit_protons_cut_all", "P_hod_goodscinhit; SHMS_hod_goodscinhit; Counts", 220, 0.6, 1.4)
P_hod_goodstarttime_protons_cut_all = ROOT.TH1D("h1_P_hod_goodstarttime_protons_cut_all", "P_hod_goodstarttime; SHMS_hod_goodstarttime; Counts", 220, 0.6, 1.4)
P_cal_etotnorm_protons_cut_all = ROOT.TH1D("h1_P_cal_etotnorm_protons_cut_all", "P_cal_etotnorm; SHMS_cal_etotnorm; Counts", 220, 0, 1.5)
P_cal_etottracknorm_protons_cut_all = ROOT.TH1D("h1_P_cal_etottracknorm_protons_cut_all", "P_cal_etottracknorm; SHMS_cal_etottracknorm; Counts", 220, 0, 1.5)
P_hgcer_npeSum_protons_cut_all = ROOT.TH1D("h1_P_hgcer_npeSum_protons_cut_all", "P_hgcer_npeSum; SHMS_hgcer_npeSum; Counts", 220, 0, 0.5)
P_hgcer_xAtCer_protons_cut_all = ROOT.TH1D("h1_P_hgcer_xAtCer_protons_cut_all", "P_hgcer_xAtCer; SHMS_hgcer_xAtCer; Counts", 220, -40, 40)
P_hgcer_yAtCer_protons_cut_all = ROOT.TH1D("h1_P_hgcer_yAtCer_protons_cut_all", "P_hgcer_yAtCer; SHMS_hgcer_yAtCer; Counts", 220, -40, 40)
P_aero_npeSum_protons_cut_all = ROOT.TH1D("h1_P_aero_npeSum_protons_cut_all", "P_aero_npeSum; SHMS_aero_npeSum; Counts", 220, 1, 50)
P_aero_xAtAero_protons_cut_all = ROOT.TH1D("h1_P_acero_xAtAero_protons_cut_all", "P_aero_xAtAero; SHMS_aero_xAtAero; Counts", 220, -40, 40)
P_aero_yAtAero_protons_cut_all = ROOT.TH1D("h1_P_aero_yAtAero_protons_cut_all", "P_aero_yAtAero; SHMS_aero_yAtAero; Counts", 220, -40, 40)
P_kin_MMp_protons_cut_all = ROOT.TH1D("h1_P_kin_MMp_protons_cut_all", "P_kin_MMp; MM_{p}; Counts", 220, 0.5, 1.8)
P_RFTime_Dist_protons_cut_all = ROOT.TH1D("h1_P_RFTime_Dist_protons_cut_all", "P_RFTime_Dist; SHMS_RFTime; Counts", 220, -1, 5)
CTime_epCoinTime_ROC1_protons_cut_all = ROOT.TH1D("h1_CTime_epCoinTime_ROC1_protons_cut_all", "CTime_epCoinTime_ROC1; e p Coin_Time; Counts", 220, -50, 50)
Q2_protons_cut_all = ROOT.TH1D("h1_Q2_protons_cut_all", "Q2; Q2; Counts", 220, -4, 10)
W_protons_cut_all = ROOT.TH1D("h1_W_protons_cut_all", "W; W; Counts", 220, -4, 10)
epsilon_protons_cut_all = ROOT.TH1D("h1_epsilon_protons_cut_all", "epsilon; epsilon; Counts", 220, -6, 6)

P_gtr_beta_protons_cut_prompt = ROOT.TH1D("h1_P_gtr_beta_protons_cut_prompt", "P_gtr_beta; SHMS_#beta; Counts", 220, 0.6, 1.4)
P_RFTime_Dist_protons_cut_prompt = ROOT.TH1D("h1_P_RFTime_Dist_protons_cut_prompt", "P_RFTime_Dist; SHMS_RFTime; Counts", 220, -1, 5)
CTime_epCoinTime_ROC1_protons_cut_prompt = ROOT.TH1D("h1_CTime_epCoinTime_ROC1_protons_cut_prompt", "CTime_epCoinTime_ROC1; e p Coin_Time; Counts", 220, -8, 8)
P_kin_MMp_protons_cut_prompt = ROOT.TH1D("h1_P_kin_MMp_protons_cut_prompt", "P_kin_MMp; MM_{p}; Counts", 220, 0.5, 1.8)

P_gtr_beta_protons_cut_random = ROOT.TH1D("h1_P_gtr_beta_protons_cut_random", "P_gtr_beta; SHMS_#beta; Counts", 220, 0.6, 1.4)
P_RFTime_Dist_protons_cut_random = ROOT.TH1D("h1_P_RFTime_Dist_protons_cut_random", "P_RFTime_Dist; SHMS_RFTime; Counts", 220, -1, 5)
CTime_epCoinTime_ROC1_protons_cut_random = ROOT.TH1D("h1_CTime_epCoinTime_ROC1_protons_cut_random", "CTime_epCoinTime_ROC1; e p Coin_Time; Counts", 220, -40, 40)
P_kin_MMp_protons_cut_random = ROOT.TH1D("h1_P_kin_MMp_protons_cut_random", "P_kin_MMp; MM_{p}; Counts", 220, 0.5, 1.8)

CTime_epCoinTime_ROC1_protons_cut_random_scaled = ROOT.TH1D("h1_CTime_epCoinTime_ROC1_protons_cut_random_scaled", "CTime_epCoinTime_ROC1; e p Coin_Time; Counts", 220, -40, 40)
CTime_epCoinTime_ROC1_protons_cut_random_sub = ROOT.TH1D("h1_CTime_epCoinTime_ROC1_protons_cut_random_sub", "CTime_epCoinTime_ROC1; e p Coin_Time; Counts", 220, -8, 8)
P_kin_MMp_protons_cut_random_scaled = ROOT.TH1D("h1_P_kin_MMp_protons_cut_random_scaled", "P_kin_MMp; MM_{p}; Counts", 220, 0.5, 1.8)
P_kin_MMp_protons_cut_random_sub = ROOT.TH1D("h1_P_kin_MMp_protons_cut_random_sub", "P_kin_MMp; MM_{p}; Counts", 220, 0.5, 1.8)

###############################################################################################################################################

# 2D Histograms
P_hgcer_npeSum_vs_aero_npeSum_pions_uncut = ROOT.TH2D("h2_P_hgcer_npeSum_vs_aero_npeSum_pions_uncut", "P_hgcer_npeSum vs P_aero_npeSum; SHMS_hgcer_npeSum; SHMS_aero_npeSum", 100, 0, 50, 100, 0, 50)
CTime_ePiCoinTime_ROC1_vs_P_kin_MMpi_pions_uncut = ROOT.TH2D("h2_CTime_ePiCoinTime_ROC1_vs_P_kin_MMpi_pions_uncut", "CTime_ePiCoinTime_ROC1 vs P_kin_MMpi; e #pi Coin_Time; MM_{#pi}", 100, -2, 2, 100, 0, 3)
P_hgcer_xAtCer_vs_hgcer_yAtCer_pions_uncut = ROOT.TH2D("h2_P_hgcer_xAtCer_vs_hgcer_yAtCer_pions_uncut", "P_hgcer_xAtCer vs P_hgcer_yAtCer; SHMS_hgcer_xAtCer; SHMS_hgcer_yAtCer", 100, -10, 10, 100, -10, 10)

P_hgcer_npeSum_vs_aero_npeSum_pions_cut_all = ROOT.TH2D("h2_P_hgcer_npeSum_vs_aero_npeSum_pions_cut_all", "P_hgcer_npeSum vs P_aero_npeSum; SHMS_hgcer_npeSum; SHMS_aero_npeSum", 100, 0, 50, 100, 0, 50)
CTime_ePiCoinTime_ROC1_vs_P_kin_MMpi_pions_cut_all = ROOT.TH2D("h2_CTime_ePiCoinTime_ROC1_vs_P_kin_MMpi_pions_cut_all", "CTime_ePiCoinTime_ROC1 vs P_kin_MMpi; e #pi Coin_Time; MM_{#pi}", 100, -1, 1, 100, 0.8, 1.6)
P_hgcer_xAtCer_vs_hgcer_yAtCer_pions_cut_all = ROOT.TH2D("h2_P_hgcer_xAtCer_vs_hgcer_yAtCer_pions_cut_all", "P_hgcer_xAtCer vs P_hgcer_yAtCer; SHMS_hgcer_xAtCer; SHMS_hgcer_yAtCer", 100, -32, 32, 100, -30, 30)

CTime_ePiCoinTime_ROC1_vs_P_kin_MMpi_pions_cut_prompt = ROOT.TH2D("h2_CTime_ePiCoinTime_ROC1_vs_P_kin_MMpi_pions_cut_prompt", "CTime_ePiCoinTime_ROC1 vs P_kin_MMpi; e #pi Coin_Time; MM_{#pi}", 100, -1, 1, 100, 0.8, 1.6)

P_hgcer_npeSum_vs_aero_npeSum_kaons_uncut = ROOT.TH2D("h2_P_hgcer_npeSum_vs_aero_npeSum_kaons_uncut", "P_hgcer_npeSum vs P_aero_npeSum; SHMS_hgcer_npeSum; SHMS_aero_npeSum", 100, 0, 50, 100, 0, 50)
CTime_eKCoinTime_ROC1_vs_P_kin_MMK_kaons_uncut = ROOT.TH2D("h2_CTime_eKCoinTime_ROC1_vs_P_kin_MMK_kaons_uncut", "CTime_eKCoinTime_ROC1 vs P_kin_MMK; e K Coin_Time; MM_{K}", 100, -2, 2, 100, 0, 3)
P_hgcer_xAtCer_vs_hgcer_yAtCer_kaons_uncut = ROOT.TH2D("h2_P_hgcer_xAtCer_vs_hgcer_yAtCer_kaons_uncut", "P_hgcer_xAtCer vs P_hgcer_yAtCer; SHMS_hgcer_xAtCer; SHMS_hgcer_yAtCer", 100, -10, 10, 100, -10, 10)

P_hgcer_npeSum_vs_aero_npeSum_kaons_cut_all = ROOT.TH2D("h2_P_hgcer_npeSum_vs_aero_npeSum_kaons_cut_all", "P_hgcer_npeSum vs P_aero_npeSum; SHMS_hgcer_npeSum; SHMS_aero_npeSum", 100, 0, 50, 100, 0, 50)
CTime_eKCoinTime_ROC1_vs_P_kin_MMK_kaons_cut_all = ROOT.TH2D("h2_CTime_eKCoinTime_ROC1_vs_P_kin_MMK_kaons_cut_all", "CTime_eKCoinTime_ROC1 vs P_kin_MMK; e K Coin_Time; MM_{K}", 100, -1, 1, 100, 0.6, 1.6)
P_hgcer_xAtCer_vs_hgcer_yAtCer_kaons_cut_all = ROOT.TH2D("h2_P_hgcer_xAtCer_vs_hgcer_yAtCer_kaons_cut_all", "P_hgcer_xAtCer vs P_hgcer_yAtCer; SHMS_hgcer_xAtCer; SHMS_hgcer_yAtCer", 100, -32, 32, 100, -30, 30)

CTime_eKCoinTime_ROC1_vs_P_kin_MMK_kaons_cut_prompt = ROOT.TH2D("h2_CTime_eKCoinTime_ROC1_vs_P_kin_MMK_kaons_cut_prompt", "CTime_eKCoinTime_ROC1 vs P_kin_MMK; e K Coin_Time; MM_{K}", 100, -1, 1, 100, 0.6, 1.6)

P_hgcer_npeSum_vs_aero_npeSum_protons_uncut = ROOT.TH2D("h2_P_hgcer_npeSum_vs_aero_npeSum_protons_uncut", "P_hgcer_npeSum vs P_aero_npeSum; SHMS_hgcer_npeSum; SHMS_aero_npeSum", 100, 0, 50, 100, 0, 50)
CTime_epCoinTime_ROC1_vs_P_kin_MMp_protons_uncut = ROOT.TH2D("h2_CTime_epCoinTime_ROC1_vs_P_kin_MMp_protons_uncut", "CTime_epCoinTime_ROC1 vs P_kin_MMp; e p Coin_Time; MM_{p}", 100, -2, 2, 100, 0, 3)
P_hgcer_xAtCer_vs_hgcer_yAtCer_protons_uncut = ROOT.TH2D("h2_P_hgcer_xAtCer_vs_hgcer_yAtCer_protons_uncut", "P_hgcer_xAtCer vs P_hgcer_yAtCer; SHMS_hgcer_xAtCer; SHMS_hgcer_yAtCer", 100, -10, 10, 100, -10, 10)

P_hgcer_npeSum_vs_aero_npeSum_protons_cut_all = ROOT.TH2D("h2_P_hgcer_npeSum_vs_aero_npeSum_protons_cut_all", "P_hgcer_npeSum vs P_aero_npeSum; SHMS_hgcer_npeSum; SHMS_aero_npeSum", 100, 0, 50, 100, 0, 50)
CTime_epCoinTime_ROC1_vs_P_kin_MMp_protons_cut_all = ROOT.TH2D("h2_CTime_epCoinTime_ROC1_vs_P_kin_MMp_protons_cut_all", "CTime_epCoinTime_ROC1 vs P_kin_MMp; e p Coin_Time; MM_{p}", 100, -1, 1, 100, 0.4, 1.6)
P_hgcer_xAtCer_vs_hgcer_yAtCer_protons_cut_all = ROOT.TH2D("h2_P_hgcer_xAtCer_vs_hgcer_yAtCer_protons_cut_all", "P_hgcer_xAtCer vs P_hgcer_yAtCer; SHMS_hgcer_xAtCer; SHMS_hgcer_yAtCer", 100, -32, 32, 100, -30, 30)

CTime_epCoinTime_ROC1_vs_P_kin_MMp_protons_cut_prompt = ROOT.TH2D("h2_CTime_epCoinTime_ROC1_vs_P_kin_MMp_protons_cut_prompt", "CTime_epCoinTime_ROC1 vs P_kin_MMp; e p Coin_Time; MM_{p}", 100, -1, 1, 100, 0.4, 1.6)

#################################################################################################################################################

# Filling Histograms for Pions
for event in Uncut_Pion_Events_tree:
    H_gtr_beta_pions_uncut.Fill(event.H_gtr_beta)
    H_gtr_xp_pions_uncut.Fill(event.H_gtr_xp)
    H_gtr_yp_pions_uncut.Fill(event.H_gtr_yp)
    H_gtr_dp_pions_uncut.Fill(event.H_gtr_dp)
    H_hod_goodscinhit_pions_uncut.Fill(event.H_hod_goodscinhit)
    H_hod_goodstarttime_pions_uncut.Fill(event.H_hod_goodstarttime)
    H_cal_etotnorm_pions_uncut.Fill(event.H_cal_etotnorm)
    H_cal_etottracknorm_pions_uncut.Fill(event.H_cal_etottracknorm)
    H_cer_npeSum_pions_uncut.Fill(event.H_cer_npeSum)
    H_RFTime_Dist_pions_uncut.Fill(event.H_RF_Dist)
    P_gtr_beta_pions_uncut.Fill(event.P_gtr_beta)
    P_gtr_xp_pions_uncut.Fill(event.P_gtr_xp)
    P_gtr_yp_pions_uncut.Fill(event.P_gtr_yp)
    P_gtr_dp_pions_uncut.Fill(event.P_gtr_dp)
    P_gtr_p_pions_uncut.Fill(event.P_gtr_p)
    P_hod_goodscinhit_pions_uncut.Fill(event.P_hod_goodscinhit)
    P_hod_goodstarttime_pions_uncut.Fill(event.P_hod_goodstarttime)
    P_cal_etotnorm_pions_uncut.Fill(event.P_cal_etotnorm)
    P_cal_etottracknorm_pions_uncut.Fill(event.P_cal_etottracknorm)
    P_hgcer_npeSum_pions_uncut.Fill(event.P_hgcer_npeSum)
    P_hgcer_xAtCer_pions_uncut.Fill(event.P_hgcer_xAtCer)
    P_hgcer_yAtCer_pions_uncut.Fill(event.P_hgcer_yAtCer)
    P_aero_npeSum_pions_uncut.Fill(event.P_aero_npeSum)
    P_aero_xAtAero_pions_uncut.Fill(event.P_aero_xAtAero)
    P_aero_yAtAero_pions_uncut.Fill(event.P_aero_yAtAero)
    P_kin_MMpi_pions_uncut.Fill(event.MMpi)
    P_RFTime_Dist_pions_uncut.Fill(event.P_RF_Dist)
    CTime_ePiCoinTime_ROC1_pions_uncut.Fill(event.CTime_ePiCoinTime_ROC1)
    Q2_pions_uncut.Fill(event.Q2)
    W_pions_uncut.Fill(event.W)
    epsilon_pions_uncut.Fill(event.epsilon)
    P_hgcer_npeSum_vs_aero_npeSum_pions_uncut.Fill(event.P_hgcer_npeSum, event.P_aero_npeSum)
    CTime_ePiCoinTime_ROC1_vs_P_kin_MMpi_pions_uncut.Fill(event.CTime_ePiCoinTime_ROC1, event.MMpi)
    P_hgcer_xAtCer_vs_hgcer_yAtCer_pions_uncut.Fill(event.P_hgcer_xAtCer, event.P_hgcer_yAtCer)

for event in Cut_Pion_Events_All_tree:
    H_gtr_beta_pions_cut_all.Fill(event.H_gtr_beta)
    H_gtr_xp_pions_cut_all.Fill(event.H_gtr_xp)
    H_gtr_yp_pions_cut_all.Fill(event.H_gtr_yp)
    H_gtr_dp_pions_cut_all.Fill(event.H_gtr_dp)
    H_hod_goodscinhit_pions_cut_all.Fill(event.H_hod_goodscinhit)
    H_hod_goodstarttime_pions_cut_all.Fill(event.H_hod_goodstarttime)
    H_cal_etotnorm_pions_cut_all.Fill(event.H_cal_etotnorm)
    H_cal_etottracknorm_pions_cut_all.Fill(event.H_cal_etottracknorm)
    H_cer_npeSum_pions_cut_all.Fill(event.H_cer_npeSum)
    H_RFTime_Dist_pions_cut_all.Fill(event.H_RF_Dist)
    P_gtr_beta_pions_cut_all.Fill(event.P_gtr_beta)
    P_gtr_xp_pions_cut_all.Fill(event.P_gtr_xp)
    P_gtr_yp_pions_cut_all.Fill(event.P_gtr_yp)
    P_gtr_dp_pions_cut_all.Fill(event.P_gtr_dp)
    P_gtr_p_pions_cut_all.Fill(event.P_gtr_p)
    P_hod_goodscinhit_pions_cut_all.Fill(event.P_hod_goodscinhit)
    P_hod_goodstarttime_pions_cut_all.Fill(event.P_hod_goodstarttime)
    P_cal_etotnorm_pions_cut_all.Fill(event.P_cal_etotnorm)
    P_cal_etottracknorm_pions_cut_all.Fill(event.P_cal_etottracknorm)
    P_hgcer_npeSum_pions_cut_all.Fill(event.P_hgcer_npeSum)
    P_hgcer_xAtCer_pions_cut_all.Fill(event.P_hgcer_xAtCer)
    P_hgcer_yAtCer_pions_cut_all.Fill(event.P_hgcer_yAtCer)
    P_aero_npeSum_pions_cut_all.Fill(event.P_aero_npeSum)
    P_aero_xAtAero_pions_cut_all.Fill(event.P_aero_xAtAero)
    P_aero_yAtAero_pions_cut_all.Fill(event.P_aero_yAtAero)
    P_kin_MMpi_pions_cut_all.Fill(event.MMpi)
    P_RFTime_Dist_pions_cut_all.Fill(event.P_RF_Dist)
    CTime_ePiCoinTime_ROC1_pions_cut_all.Fill(event.CTime_ePiCoinTime_ROC1)
    Q2_pions_cut_all.Fill(event.Q2)
    W_pions_cut_all.Fill(event.W)
    epsilon_pions_cut_all.Fill(event.epsilon)
    P_hgcer_npeSum_vs_aero_npeSum_pions_cut_all.Fill(event.P_hgcer_npeSum, event.P_aero_npeSum)
    CTime_ePiCoinTime_ROC1_vs_P_kin_MMpi_pions_cut_all.Fill(event.CTime_ePiCoinTime_ROC1, event.MMpi)
    P_hgcer_xAtCer_vs_hgcer_yAtCer_pions_cut_all.Fill(event.P_hgcer_xAtCer, event.P_hgcer_yAtCer)
    
for event in Cut_Pion_Events_Prompt_tree:
    P_gtr_beta_pions_cut_prompt.Fill(event.P_gtr_beta)
    P_RFTime_Dist_pions_cut_prompt.Fill(event.P_RF_Dist)
    CTime_ePiCoinTime_ROC1_pions_cut_prompt.Fill(event.CTime_ePiCoinTime_ROC1)
    P_kin_MMpi_pions_cut_prompt.Fill(event.MMpi)
    CTime_ePiCoinTime_ROC1_vs_P_kin_MMpi_pions_cut_prompt.Fill(event.CTime_ePiCoinTime_ROC1, event.MMpi)

for event in Cut_Pion_Events_Random_tree:
    P_gtr_beta_pions_cut_random.Fill(event.P_gtr_beta)
    P_RFTime_Dist_pions_cut_random.Fill(event.P_RF_Dist)
    CTime_ePiCoinTime_ROC1_pions_cut_random.Fill(event.CTime_ePiCoinTime_ROC1)
    P_kin_MMpi_pions_cut_random.Fill(event.MMpi)

##############################################################################################################################################

# Filling Histograms for Kaons                                                                                                                                                                                                              
for event in Uncut_Kaon_Events_tree:
    H_gtr_beta_kaons_uncut.Fill(event.H_gtr_beta)
    H_gtr_xp_kaons_uncut.Fill(event.H_gtr_xp)
    H_gtr_yp_kaons_uncut.Fill(event.H_gtr_yp)
    H_gtr_dp_kaons_uncut.Fill(event.H_gtr_dp)
    H_hod_goodscinhit_kaons_uncut.Fill(event.H_hod_goodscinhit)
    H_hod_goodstarttime_kaons_uncut.Fill(event.H_hod_goodstarttime)
    H_cal_etotnorm_kaons_uncut.Fill(event.H_cal_etotnorm)
    H_cal_etottracknorm_kaons_uncut.Fill(event.H_cal_etottracknorm)
    H_cer_npeSum_kaons_uncut.Fill(event.H_cer_npeSum)
    H_RFTime_Dist_kaons_uncut.Fill(event.H_RF_Dist)
    P_gtr_beta_kaons_uncut.Fill(event.P_gtr_beta)
    P_gtr_xp_kaons_uncut.Fill(event.P_gtr_xp)
    P_gtr_yp_kaons_uncut.Fill(event.P_gtr_yp)
    P_gtr_dp_kaons_uncut.Fill(event.P_gtr_dp)
    P_gtr_p_kaons_uncut.Fill(event.P_gtr_p)
    P_hod_goodscinhit_kaons_uncut.Fill(event.P_hod_goodscinhit)
    P_hod_goodstarttime_kaons_uncut.Fill(event.P_hod_goodstarttime)
    P_cal_etotnorm_kaons_uncut.Fill(event.P_cal_etotnorm)
    P_cal_etottracknorm_kaons_uncut.Fill(event.P_cal_etottracknorm)
    P_hgcer_npeSum_kaons_uncut.Fill(event.P_hgcer_npeSum)
    P_hgcer_xAtCer_kaons_uncut.Fill(event.P_hgcer_xAtCer)
    P_hgcer_yAtCer_kaons_uncut.Fill(event.P_hgcer_yAtCer)
    P_aero_npeSum_kaons_uncut.Fill(event.P_aero_npeSum)
    P_aero_xAtAero_kaons_uncut.Fill(event.P_aero_xAtAero)
    P_aero_yAtAero_kaons_uncut.Fill(event.P_aero_yAtAero)
    P_kin_MMK_kaons_uncut.Fill(event.MMK)
    P_RFTime_Dist_kaons_uncut.Fill(event.P_RF_Dist)
    CTime_eKCoinTime_ROC1_kaons_uncut.Fill(event.CTime_eKCoinTime_ROC1)
    Q2_kaons_uncut.Fill(event.Q2)
    W_kaons_uncut.Fill(event.W)
    epsilon_kaons_uncut.Fill(event.epsilon)
    P_hgcer_npeSum_vs_aero_npeSum_kaons_uncut.Fill(event.P_hgcer_npeSum, event.P_aero_npeSum)
    CTime_eKCoinTime_ROC1_vs_P_kin_MMK_kaons_uncut.Fill(event.CTime_eKCoinTime_ROC1, event.MMK)
    P_hgcer_xAtCer_vs_hgcer_yAtCer_kaons_uncut.Fill(event.P_hgcer_xAtCer, event.P_hgcer_yAtCer)

for event in Cut_Kaon_Events_All_tree:
    H_gtr_beta_kaons_cut_all.Fill(event.H_gtr_beta)
    H_gtr_xp_kaons_cut_all.Fill(event.H_gtr_xp)
    H_gtr_yp_kaons_cut_all.Fill(event.H_gtr_yp)
    H_gtr_dp_kaons_cut_all.Fill(event.H_gtr_dp)
    H_hod_goodscinhit_kaons_cut_all.Fill(event.H_hod_goodscinhit)
    H_hod_goodstarttime_kaons_cut_all.Fill(event.H_hod_goodstarttime)
    H_cal_etotnorm_kaons_cut_all.Fill(event.H_cal_etotnorm)
    H_cal_etottracknorm_kaons_cut_all.Fill(event.H_cal_etottracknorm)
    H_cer_npeSum_kaons_cut_all.Fill(event.H_cer_npeSum)
    H_RFTime_Dist_kaons_cut_all.Fill(event.H_RF_Dist)
    P_gtr_beta_kaons_cut_all.Fill(event.P_gtr_beta)
    P_gtr_xp_kaons_cut_all.Fill(event.P_gtr_xp)
    P_gtr_yp_kaons_cut_all.Fill(event.P_gtr_yp)
    P_gtr_dp_kaons_cut_all.Fill(event.P_gtr_dp)
    P_gtr_p_kaons_cut_all.Fill(event.P_gtr_p)
    P_hod_goodscinhit_kaons_cut_all.Fill(event.P_hod_goodscinhit)
    P_hod_goodstarttime_kaons_cut_all.Fill(event.P_hod_goodstarttime)
    P_cal_etotnorm_kaons_cut_all.Fill(event.P_cal_etotnorm)
    P_cal_etottracknorm_kaons_cut_all.Fill(event.P_cal_etottracknorm)
    P_hgcer_npeSum_kaons_cut_all.Fill(event.P_hgcer_npeSum)
    P_hgcer_xAtCer_kaons_cut_all.Fill(event.P_hgcer_xAtCer)
    P_hgcer_yAtCer_kaons_cut_all.Fill(event.P_hgcer_yAtCer)
    P_aero_npeSum_kaons_cut_all.Fill(event.P_aero_npeSum)
    P_aero_xAtAero_kaons_cut_all.Fill(event.P_aero_xAtAero)
    P_aero_yAtAero_kaons_cut_all.Fill(event.P_aero_yAtAero)
    P_kin_MMK_kaons_cut_all.Fill(event.MMK)
    P_RFTime_Dist_kaons_cut_all.Fill(event.P_RF_Dist)
    CTime_eKCoinTime_ROC1_kaons_cut_all.Fill(event.CTime_eKCoinTime_ROC1)
    Q2_kaons_cut_all.Fill(event.Q2)
    W_kaons_cut_all.Fill(event.W)
    epsilon_kaons_cut_all.Fill(event.epsilon)
    P_hgcer_npeSum_vs_aero_npeSum_kaons_cut_all.Fill(event.P_hgcer_npeSum, event.P_aero_npeSum)
    CTime_eKCoinTime_ROC1_vs_P_kin_MMK_kaons_cut_all.Fill(event.CTime_eKCoinTime_ROC1, event.MMK)
    P_hgcer_xAtCer_vs_hgcer_yAtCer_kaons_cut_all.Fill(event.P_hgcer_xAtCer, event.P_hgcer_yAtCer)

for event in Cut_Kaon_Events_Prompt_tree:
    P_gtr_beta_kaons_cut_prompt.Fill(event.P_gtr_beta)
    P_RFTime_Dist_kaons_cut_prompt.Fill(event.P_RF_Dist)
    CTime_eKCoinTime_ROC1_kaons_cut_prompt.Fill(event.CTime_eKCoinTime_ROC1)
    P_kin_MMK_kaons_cut_prompt.Fill(event.MMK)
    CTime_eKCoinTime_ROC1_vs_P_kin_MMK_kaons_cut_prompt.Fill(event.CTime_eKCoinTime_ROC1, event.MMK)

for event in Cut_Kaon_Events_Random_tree:
    P_gtr_beta_kaons_cut_random.Fill(event.P_gtr_beta)
    P_RFTime_Dist_kaons_cut_random.Fill(event.P_RF_Dist)
    CTime_eKCoinTime_ROC1_kaons_cut_random.Fill(event.CTime_eKCoinTime_ROC1)
    P_kin_MMK_kaons_cut_random.Fill(event.MMK)

#############################################################################################################################################

# Filling Histograms for Protons   
for event in Uncut_Proton_Events_tree:
    H_gtr_beta_protons_uncut.Fill(event.H_gtr_beta)
    H_gtr_xp_protons_uncut.Fill(event.H_gtr_xp)
    H_gtr_yp_protons_uncut.Fill(event.H_gtr_yp)
    H_gtr_dp_protons_uncut.Fill(event.H_gtr_dp)
    H_hod_goodscinhit_protons_uncut.Fill(event.H_hod_goodscinhit)
    H_hod_goodstarttime_protons_uncut.Fill(event.H_hod_goodstarttime)
    H_cal_etotnorm_protons_uncut.Fill(event.H_cal_etotnorm)
    H_cal_etottracknorm_protons_uncut.Fill(event.H_cal_etottracknorm)
    H_cer_npeSum_protons_uncut.Fill(event.H_cer_npeSum)
    H_RFTime_Dist_protons_uncut.Fill(event.H_RF_Dist)
    P_gtr_beta_protons_uncut.Fill(event.P_gtr_beta)
    P_gtr_xp_protons_uncut.Fill(event.P_gtr_xp)
    P_gtr_yp_protons_uncut.Fill(event.P_gtr_yp)
    P_gtr_dp_protons_uncut.Fill(event.P_gtr_dp)
    P_gtr_p_protons_uncut.Fill(event.P_gtr_p)
    P_hod_goodscinhit_protons_uncut.Fill(event.P_hod_goodscinhit)
    P_hod_goodstarttime_protons_uncut.Fill(event.P_hod_goodstarttime)
    P_cal_etotnorm_protons_uncut.Fill(event.P_cal_etotnorm)
    P_cal_etottracknorm_protons_uncut.Fill(event.P_cal_etottracknorm)
    P_hgcer_npeSum_protons_uncut.Fill(event.P_hgcer_npeSum)
    P_hgcer_xAtCer_protons_uncut.Fill(event.P_hgcer_xAtCer)
    P_hgcer_yAtCer_protons_uncut.Fill(event.P_hgcer_yAtCer)
    P_aero_npeSum_protons_uncut.Fill(event.P_aero_npeSum)
    P_aero_xAtAero_protons_uncut.Fill(event.P_aero_xAtAero)
    P_aero_yAtAero_protons_uncut.Fill(event.P_aero_yAtAero)
    P_kin_MMp_protons_uncut.Fill(event.MMp)
    P_RFTime_Dist_protons_uncut.Fill(event.P_RF_Dist)
    CTime_epCoinTime_ROC1_protons_uncut.Fill(event.CTime_epCoinTime_ROC1)
    Q2_protons_uncut.Fill(event.Q2)
    W_protons_uncut.Fill(event.W)
    epsilon_protons_uncut.Fill(event.epsilon)
    P_hgcer_npeSum_vs_aero_npeSum_protons_uncut.Fill(event.P_hgcer_npeSum, event.P_aero_npeSum)
    CTime_epCoinTime_ROC1_vs_P_kin_MMp_protons_uncut.Fill(event.CTime_epCoinTime_ROC1, event.MMp)
    P_hgcer_xAtCer_vs_hgcer_yAtCer_protons_uncut.Fill(event.P_hgcer_xAtCer, event.P_hgcer_yAtCer)

for event in Cut_Proton_Events_All_tree:
    H_gtr_beta_protons_cut_all.Fill(event.H_gtr_beta)
    H_gtr_xp_protons_cut_all.Fill(event.H_gtr_xp)
    H_gtr_yp_protons_cut_all.Fill(event.H_gtr_yp)
    H_gtr_dp_protons_cut_all.Fill(event.H_gtr_dp)
    H_hod_goodscinhit_protons_cut_all.Fill(event.H_hod_goodscinhit)
    H_hod_goodstarttime_protons_cut_all.Fill(event.H_hod_goodstarttime)
    H_cal_etotnorm_protons_cut_all.Fill(event.H_cal_etotnorm)
    H_cal_etottracknorm_protons_cut_all.Fill(event.H_cal_etottracknorm)
    H_cer_npeSum_protons_cut_all.Fill(event.H_cer_npeSum)
    H_RFTime_Dist_protons_cut_all.Fill(event.H_RF_Dist)
    P_gtr_beta_protons_cut_all.Fill(event.P_gtr_beta)
    P_gtr_xp_protons_cut_all.Fill(event.P_gtr_xp)
    P_gtr_yp_protons_cut_all.Fill(event.P_gtr_yp)
    P_gtr_dp_protons_cut_all.Fill(event.P_gtr_dp)
    P_gtr_p_protons_cut_all.Fill(event.P_gtr_p)
    P_hod_goodscinhit_protons_cut_all.Fill(event.P_hod_goodscinhit)
    P_hod_goodstarttime_protons_cut_all.Fill(event.P_hod_goodstarttime)
    P_cal_etotnorm_protons_cut_all.Fill(event.P_cal_etotnorm)
    P_cal_etottracknorm_protons_cut_all.Fill(event.P_cal_etottracknorm)
    P_hgcer_npeSum_protons_cut_all.Fill(event.P_hgcer_npeSum)
    P_hgcer_xAtCer_protons_cut_all.Fill(event.P_hgcer_xAtCer)
    P_hgcer_yAtCer_protons_cut_all.Fill(event.P_hgcer_yAtCer)
    P_aero_npeSum_protons_cut_all.Fill(event.P_aero_npeSum)
    P_aero_xAtAero_protons_cut_all.Fill(event.P_aero_xAtAero)
    P_aero_yAtAero_protons_cut_all.Fill(event.P_aero_yAtAero)
    P_kin_MMp_protons_cut_all.Fill(event.MMp)
    P_RFTime_Dist_protons_cut_all.Fill(event.P_RF_Dist)
    CTime_epCoinTime_ROC1_protons_cut_all.Fill(event.CTime_epCoinTime_ROC1)
    Q2_protons_cut_all.Fill(event.Q2)
    W_protons_cut_all.Fill(event.W)
    epsilon_protons_cut_all.Fill(event.epsilon)
    P_hgcer_npeSum_vs_aero_npeSum_protons_cut_all.Fill(event.P_hgcer_npeSum, event.P_aero_npeSum)
    CTime_epCoinTime_ROC1_vs_P_kin_MMp_protons_cut_all.Fill(event.CTime_epCoinTime_ROC1, event.MMp)
    P_hgcer_xAtCer_vs_hgcer_yAtCer_protons_cut_all.Fill(event.P_hgcer_xAtCer, event.P_hgcer_yAtCer)

for event in Cut_Proton_Events_Prompt_tree:
    P_gtr_beta_protons_cut_prompt.Fill(event.P_gtr_beta)
    P_RFTime_Dist_protons_cut_prompt.Fill(event.P_RF_Dist)
    CTime_epCoinTime_ROC1_protons_cut_prompt.Fill(event.CTime_epCoinTime_ROC1)
    P_kin_MMp_protons_cut_prompt.Fill(event.MMp)
    CTime_epCoinTime_ROC1_vs_P_kin_MMp_protons_cut_prompt.Fill(event.CTime_epCoinTime_ROC1, event.MMp)

for event in Cut_Proton_Events_Random_tree:
    P_gtr_beta_protons_cut_random.Fill(event.P_gtr_beta)
    P_RFTime_Dist_protons_cut_random.Fill(event.P_RF_Dist)
    CTime_epCoinTime_ROC1_protons_cut_random.Fill(event.CTime_epCoinTime_ROC1)
    P_kin_MMp_protons_cut_random.Fill(event.MMp)

##############################################################################################################################################

outHistFile = ROOT.TFile.Open("%s/%s_%s_Output_Data.root" % (OUTPATH, runNum, MaxEvent), "RECREATE")                                                                                               
     
d_Uncut_Pion_Events = outHistFile.mkdir("Uncut_Pion_Events")
d_Cut_Pion_Events_All = outHistFile.mkdir("Cut_Pion_Events_All")
d_Cut_Pion_Events_Prompt = outHistFile.mkdir("Cut_Pion_Events_Prompt")
d_Cut_Pion_Events_Random = outHistFile.mkdir("Cut_Pion_Events_Random")
d_Uncut_Kaon_Events = outHistFile.mkdir("Uncut_Kaon_Events")
d_Cut_Kaon_Events_All = outHistFile.mkdir("Cut_Kaon_Events_All")
d_Cut_Kaon_Events_Prompt = outHistFile.mkdir("Cut_Kaon_Events_Prompt")
d_Cut_Kaon_Events_Random = outHistFile.mkdir("Cut_Kaon_Events_Random")
d_Uncut_Proton_Events = outHistFile.mkdir("Uncut_Proton_Events")
d_Cut_Proton_Events_All = outHistFile.mkdir("Cut_Proton_Events_All")
d_Cut_Proton_Events_Prompt = outHistFile.mkdir("Cut_Proton_Events_Prompt")
d_Cut_Proton_Events_Random = outHistFile.mkdir("Cut_Proton_Events_Random")

# Writing Histograms                                                                                                                                                                                                                        
d_Uncut_Pion_Events.cd()
H_gtr_beta_pions_uncut.Write()
H_gtr_xp_pions_uncut.Write()
H_gtr_yp_pions_uncut.Write()
H_gtr_dp_pions_uncut.Write()
H_hod_goodscinhit_pions_uncut.Write()
H_hod_goodstarttime_pions_uncut.Write()
H_cal_etotnorm_pions_uncut.Write()
H_cal_etottracknorm_pions_uncut.Write()
H_cer_npeSum_pions_uncut.Write()
H_RFTime_Dist_pions_uncut.Write()
P_gtr_beta_pions_uncut.Write()
P_gtr_xp_pions_uncut.Write()
P_gtr_yp_pions_uncut.Write()
P_gtr_dp_pions_uncut.Write()
P_gtr_p_pions_uncut.Write()
P_hod_goodscinhit_pions_uncut.Write()
P_hod_goodstarttime_pions_uncut.Write()
P_cal_etotnorm_pions_uncut.Write()
P_cal_etottracknorm_pions_uncut.Write()
P_hgcer_npeSum_pions_uncut.Write()
P_hgcer_xAtCer_pions_uncut.Write()
P_hgcer_yAtCer_pions_uncut.Write()
P_aero_npeSum_pions_uncut.Write()
P_aero_xAtAero_pions_uncut.Write()
P_aero_yAtAero_pions_uncut.Write()
P_kin_MMpi_pions_uncut.Write()
P_RFTime_Dist_pions_uncut.Write()
CTime_ePiCoinTime_ROC1_pions_uncut.Write()
Q2_pions_uncut.Write()
W_pions_uncut.Write()
epsilon_pions_uncut.Write()
P_hgcer_npeSum_vs_aero_npeSum_pions_uncut.Write()
CTime_ePiCoinTime_ROC1_vs_P_kin_MMpi_pions_uncut.Write()
P_hgcer_xAtCer_vs_hgcer_yAtCer_pions_uncut.Write()

d_Cut_Pion_Events_All.cd()
H_gtr_beta_pions_cut_all.Write()
H_gtr_xp_pions_cut_all.Write()
H_gtr_yp_pions_cut_all.Write()
H_gtr_dp_pions_cut_all.Write()
H_hod_goodscinhit_pions_cut_all.Write()
H_hod_goodstarttime_pions_cut_all.Write()
H_cal_etotnorm_pions_cut_all.Write()
H_cal_etottracknorm_pions_cut_all.Write()
H_cer_npeSum_pions_cut_all.Write()
H_RFTime_Dist_pions_cut_all.Write()
P_gtr_beta_pions_cut_all.Write()
P_gtr_xp_pions_cut_all.Write()
P_gtr_yp_pions_cut_all.Write()
P_gtr_dp_pions_cut_all.Write()
P_gtr_p_pions_cut_all.Write()
P_hod_goodscinhit_pions_cut_all.Write()
P_hod_goodstarttime_pions_cut_all.Write()
P_cal_etotnorm_pions_cut_all.Write()
P_cal_etottracknorm_pions_cut_all.Write()
P_hgcer_npeSum_pions_cut_all.Write()
P_hgcer_xAtCer_pions_cut_all.Write()
P_hgcer_yAtCer_pions_cut_all.Write()
P_aero_npeSum_pions_cut_all.Write()
P_aero_xAtAero_pions_cut_all.Write()
P_aero_yAtAero_pions_cut_all.Write()
P_kin_MMpi_pions_cut_all.Write()
P_RFTime_Dist_pions_cut_all.Write()
CTime_ePiCoinTime_ROC1_pions_cut_all.Write()
Q2_pions_cut_all.Write()
W_pions_cut_all.Write()
epsilon_pions_cut_all.Write()
P_hgcer_npeSum_vs_aero_npeSum_pions_cut_all.Write()
CTime_ePiCoinTime_ROC1_vs_P_kin_MMpi_pions_cut_all.Write()
P_hgcer_xAtCer_vs_hgcer_yAtCer_pions_cut_all.Write()

d_Cut_Pion_Events_Prompt.cd()
P_gtr_beta_pions_cut_prompt.Write()
P_RFTime_Dist_pions_cut_prompt.Write()
CTime_ePiCoinTime_ROC1_pions_cut_prompt.Write()
P_kin_MMpi_pions_cut_prompt.Write()
CTime_ePiCoinTime_ROC1_vs_P_kin_MMpi_pions_cut_prompt.Write()

d_Cut_Pion_Events_Random.cd()
P_gtr_beta_pions_cut_random.Write()
P_RFTime_Dist_pions_cut_random.Write()
CTime_ePiCoinTime_ROC1_pions_cut_random.Write()
P_kin_MMpi_pions_cut_random.Write() 

d_Uncut_Kaon_Events.cd()
H_gtr_beta_kaons_uncut.Write()
H_gtr_xp_kaons_uncut.Write()
H_gtr_yp_kaons_uncut.Write()
H_gtr_dp_kaons_uncut.Write()
H_hod_goodscinhit_kaons_uncut.Write()
H_hod_goodstarttime_kaons_uncut.Write()
H_cal_etotnorm_kaons_uncut.Write()
H_cal_etottracknorm_kaons_uncut.Write()
H_cer_npeSum_kaons_uncut.Write()
H_RFTime_Dist_kaons_uncut.Write()
P_gtr_beta_kaons_uncut.Write()
P_gtr_xp_kaons_uncut.Write()
P_gtr_yp_kaons_uncut.Write()
P_gtr_dp_kaons_uncut.Write()
P_gtr_p_kaons_uncut.Write()
P_hod_goodscinhit_kaons_uncut.Write()
P_hod_goodstarttime_kaons_uncut.Write()
P_cal_etotnorm_kaons_uncut.Write()
P_cal_etottracknorm_kaons_uncut.Write()
P_hgcer_npeSum_kaons_uncut.Write()
P_hgcer_xAtCer_kaons_uncut.Write()
P_hgcer_yAtCer_kaons_uncut.Write()
P_aero_npeSum_kaons_uncut.Write()
P_aero_xAtAero_kaons_uncut.Write()
P_aero_yAtAero_kaons_uncut.Write()
P_kin_MMK_kaons_uncut.Write()
P_RFTime_Dist_kaons_uncut.Write()
CTime_eKCoinTime_ROC1_kaons_uncut.Write()
Q2_kaons_uncut.Write()
W_kaons_uncut.Write()
epsilon_kaons_uncut.Write()
P_hgcer_npeSum_vs_aero_npeSum_kaons_uncut.Write()
CTime_eKCoinTime_ROC1_vs_P_kin_MMK_kaons_uncut.Write()
P_hgcer_xAtCer_vs_hgcer_yAtCer_kaons_uncut.Write()

d_Cut_Kaon_Events_All.cd()
H_gtr_beta_kaons_cut_all.Write()
H_gtr_xp_kaons_cut_all.Write()
H_gtr_yp_kaons_cut_all.Write()
H_gtr_dp_kaons_cut_all.Write()
H_hod_goodscinhit_kaons_cut_all.Write()
H_hod_goodstarttime_kaons_cut_all.Write()
H_cal_etotnorm_kaons_cut_all.Write()
H_cal_etottracknorm_kaons_cut_all.Write()
H_cer_npeSum_kaons_cut_all.Write()
H_RFTime_Dist_kaons_cut_all.Write()
P_gtr_beta_kaons_cut_all.Write()
P_gtr_xp_kaons_cut_all.Write()
P_gtr_yp_kaons_cut_all.Write()
P_gtr_dp_kaons_cut_all.Write()
P_gtr_p_kaons_cut_all.Write()
P_hod_goodscinhit_kaons_cut_all.Write()
P_hod_goodstarttime_kaons_cut_all.Write()
P_cal_etotnorm_kaons_cut_all.Write()
P_cal_etottracknorm_kaons_cut_all.Write()
P_hgcer_npeSum_kaons_cut_all.Write()
P_hgcer_xAtCer_kaons_cut_all.Write()
P_hgcer_yAtCer_kaons_cut_all.Write()
P_aero_npeSum_kaons_cut_all.Write()
P_aero_xAtAero_kaons_cut_all.Write()
P_aero_yAtAero_kaons_cut_all.Write()
P_kin_MMK_kaons_cut_all.Write()
P_RFTime_Dist_kaons_cut_all.Write()
CTime_eKCoinTime_ROC1_kaons_cut_all.Write()
Q2_kaons_cut_all.Write()
W_kaons_cut_all.Write()
epsilon_kaons_cut_all.Write()
P_hgcer_npeSum_vs_aero_npeSum_kaons_cut_all.Write()
CTime_eKCoinTime_ROC1_vs_P_kin_MMK_kaons_cut_all.Write()
P_hgcer_xAtCer_vs_hgcer_yAtCer_kaons_cut_all.Write()

d_Cut_Kaon_Events_Prompt.cd()
P_gtr_beta_kaons_cut_prompt.Write()
P_RFTime_Dist_kaons_cut_prompt.Write()
CTime_eKCoinTime_ROC1_kaons_cut_prompt.Write()
P_kin_MMK_kaons_cut_prompt.Write()
CTime_eKCoinTime_ROC1_vs_P_kin_MMK_kaons_cut_prompt.Write()

d_Cut_Kaon_Events_Random.cd()                                                                                                                                                                                                               
P_gtr_beta_kaons_cut_random.Write()
P_RFTime_Dist_kaons_cut_random.Write()
CTime_eKCoinTime_ROC1_kaons_cut_random.Write()
P_kin_MMK_kaons_cut_random.Write()

d_Uncut_Proton_Events.cd()
H_gtr_beta_protons_uncut.Write()
H_gtr_xp_protons_uncut.Write()
H_gtr_yp_protons_uncut.Write()
H_gtr_dp_protons_uncut.Write()
H_hod_goodscinhit_protons_uncut.Write()
H_hod_goodstarttime_protons_uncut.Write()
H_cal_etotnorm_protons_uncut.Write()
H_cal_etottracknorm_protons_uncut.Write()
H_cer_npeSum_protons_uncut.Write()
H_RFTime_Dist_protons_uncut.Write()
P_gtr_beta_protons_uncut.Write()
P_gtr_xp_protons_uncut.Write()
P_gtr_yp_protons_uncut.Write()
P_gtr_dp_protons_uncut.Write()
P_gtr_p_protons_uncut.Write()
P_hod_goodscinhit_protons_uncut.Write()
P_hod_goodstarttime_protons_uncut.Write()
P_cal_etotnorm_protons_uncut.Write()
P_cal_etottracknorm_protons_uncut.Write()
P_hgcer_npeSum_protons_uncut.Write()
P_hgcer_xAtCer_protons_uncut.Write()
P_hgcer_yAtCer_protons_uncut.Write()
P_aero_npeSum_protons_uncut.Write()
P_aero_xAtAero_protons_uncut.Write()
P_aero_yAtAero_protons_uncut.Write()
P_kin_MMp_protons_uncut.Write()
P_RFTime_Dist_protons_uncut.Write()
CTime_epCoinTime_ROC1_protons_uncut.Write()
Q2_protons_uncut.Write()
W_protons_uncut.Write()
epsilon_protons_uncut.Write()
P_hgcer_npeSum_vs_aero_npeSum_protons_uncut.Write()
CTime_epCoinTime_ROC1_vs_P_kin_MMp_protons_uncut.Write()
P_hgcer_xAtCer_vs_hgcer_yAtCer_protons_uncut.Write()

d_Cut_Proton_Events_All.cd()
H_gtr_beta_protons_cut_all.Write()
H_gtr_xp_protons_cut_all.Write()
H_gtr_yp_protons_cut_all.Write()
H_gtr_dp_protons_cut_all.Write()
H_hod_goodscinhit_protons_cut_all.Write()
H_hod_goodstarttime_protons_cut_all.Write()
H_cal_etotnorm_protons_cut_all.Write()
H_cal_etottracknorm_protons_cut_all.Write()
H_cer_npeSum_protons_cut_all.Write()
H_RFTime_Dist_protons_cut_all.Write()
P_gtr_beta_protons_cut_all.Write()
P_gtr_xp_protons_cut_all.Write()
P_gtr_yp_protons_cut_all.Write()
P_gtr_dp_protons_cut_all.Write()
P_gtr_p_protons_cut_all.Write()
P_hod_goodscinhit_protons_cut_all.Write()
P_hod_goodstarttime_protons_cut_all.Write()
P_cal_etotnorm_protons_cut_all.Write()
P_cal_etottracknorm_protons_cut_all.Write()
P_hgcer_npeSum_protons_cut_all.Write()
P_hgcer_xAtCer_protons_cut_all.Write()
P_hgcer_yAtCer_protons_cut_all.Write()
P_aero_npeSum_protons_cut_all.Write()
P_aero_xAtAero_protons_cut_all.Write()
P_aero_yAtAero_protons_cut_all.Write()
P_kin_MMp_protons_cut_all.Write()
P_RFTime_Dist_protons_cut_all.Write()
CTime_epCoinTime_ROC1_protons_cut_all.Write()
Q2_protons_cut_all.Write()
W_protons_cut_all.Write()
epsilon_protons_cut_all.Write()
P_hgcer_npeSum_vs_aero_npeSum_protons_cut_all.Write()
CTime_epCoinTime_ROC1_vs_P_kin_MMp_protons_cut_all.Write()
P_hgcer_xAtCer_vs_hgcer_yAtCer_protons_cut_all.Write()

d_Cut_Proton_Events_Prompt.cd()
P_gtr_beta_protons_cut_prompt.Write()
P_RFTime_Dist_protons_cut_prompt.Write()
CTime_epCoinTime_ROC1_protons_cut_prompt.Write()
P_kin_MMp_protons_cut_prompt.Write()
CTime_epCoinTime_ROC1_vs_P_kin_MMp_protons_cut_prompt.Write()

d_Cut_Proton_Events_Random.cd()    
P_gtr_beta_protons_cut_random.Write()
P_RFTime_Dist_protons_cut_random.Write()
CTime_epCoinTime_ROC1_protons_cut_random.Write()
P_kin_MMp_protons_cut_random.Write()

outHistFile.Close()
infile.Close() 
print ("Processing Complete")
